// Code generated by ent, DO NOT EDIT.

package propertyamenity

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldLTE(FieldID, id))
}

// PropertyID applies equality check predicate on the "property_id" field. It's identical to PropertyIDEQ.
func PropertyID(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldPropertyID, v))
}

// AmenityID applies equality check predicate on the "amenity_id" field. It's identical to AmenityIDEQ.
func AmenityID(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldAmenityID, v))
}

// PropertyIDEQ applies the EQ predicate on the "property_id" field.
func PropertyIDEQ(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldPropertyID, v))
}

// PropertyIDNEQ applies the NEQ predicate on the "property_id" field.
func PropertyIDNEQ(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNEQ(FieldPropertyID, v))
}

// PropertyIDIn applies the In predicate on the "property_id" field.
func PropertyIDIn(vs ...uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldIn(FieldPropertyID, vs...))
}

// PropertyIDNotIn applies the NotIn predicate on the "property_id" field.
func PropertyIDNotIn(vs ...uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNotIn(FieldPropertyID, vs...))
}

// AmenityIDEQ applies the EQ predicate on the "amenity_id" field.
func AmenityIDEQ(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldEQ(FieldAmenityID, v))
}

// AmenityIDNEQ applies the NEQ predicate on the "amenity_id" field.
func AmenityIDNEQ(v uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNEQ(FieldAmenityID, v))
}

// AmenityIDIn applies the In predicate on the "amenity_id" field.
func AmenityIDIn(vs ...uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldIn(FieldAmenityID, vs...))
}

// AmenityIDNotIn applies the NotIn predicate on the "amenity_id" field.
func AmenityIDNotIn(vs ...uuid.UUID) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNotIn(FieldAmenityID, vs...))
}

// DetailsIsNil applies the IsNil predicate on the "details" field.
func DetailsIsNil() predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldIsNull(FieldDetails))
}

// DetailsNotNil applies the NotNil predicate on the "details" field.
func DetailsNotNil() predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.FieldNotNull(FieldDetails))
}

// HasProperty applies the HasEdge predicate on the "property" edge.
func HasProperty() predicate.PropertyAmenity {
	return predicate.PropertyAmenity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PropertyTable, PropertyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyWith applies the HasEdge predicate on the "property" edge with a given conditions (other predicates).
func HasPropertyWith(preds ...predicate.Property) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(func(s *sql.Selector) {
		step := newPropertyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAmenity applies the HasEdge predicate on the "amenity" edge.
func HasAmenity() predicate.PropertyAmenity {
	return predicate.PropertyAmenity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AmenityTable, AmenityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAmenityWith applies the HasEdge predicate on the "amenity" edge with a given conditions (other predicates).
func HasAmenityWith(preds ...predicate.Amenity) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(func(s *sql.Selector) {
		step := newAmenityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PropertyAmenity) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PropertyAmenity) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PropertyAmenity) predicate.PropertyAmenity {
	return predicate.PropertyAmenity(sql.NotPredicates(p))
}
