// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/propertyamenity"
	"github.com/google/uuid"
)

// AmenityCreate is the builder for creating a Amenity entity.
type AmenityCreate struct {
	config
	mutation *AmenityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *AmenityCreate) SetCode(v string) *AmenityCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AmenityCreate) SetName(v string) *AmenityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *AmenityCreate) SetCategory(v string) *AmenityCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AmenityCreate) SetCreatedAt(v time.Time) *AmenityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AmenityCreate) SetNillableCreatedAt(v *time.Time) *AmenityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AmenityCreate) SetID(v uuid.UUID) *AmenityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AmenityCreate) SetNillableID(v *uuid.UUID) *AmenityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (_c *AmenityCreate) AddPropertyIDs(ids ...uuid.UUID) *AmenityCreate {
	_c.mutation.AddPropertyIDs(ids...)
	return _c
}

// AddProperties adds the "properties" edges to the Property entity.
func (_c *AmenityCreate) AddProperties(v ...*Property) *AmenityCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPropertyIDs(ids...)
}

// AddPropertyAmenityIDs adds the "property_amenities" edge to the PropertyAmenity entity by IDs.
func (_c *AmenityCreate) AddPropertyAmenityIDs(ids ...int) *AmenityCreate {
	_c.mutation.AddPropertyAmenityIDs(ids...)
	return _c
}

// AddPropertyAmenities adds the "property_amenities" edges to the PropertyAmenity entity.
func (_c *AmenityCreate) AddPropertyAmenities(v ...*PropertyAmenity) *AmenityCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPropertyAmenityIDs(ids...)
}

// Mutation returns the AmenityMutation object of the builder.
func (_c *AmenityCreate) Mutation() *AmenityMutation {
	return _c.mutation
}

// Save creates the Amenity in the database.
func (_c *AmenityCreate) Save(ctx context.Context) (*Amenity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AmenityCreate) SaveX(ctx context.Context) *Amenity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AmenityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AmenityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AmenityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := amenity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := amenity.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AmenityCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Amenity.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := amenity.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Amenity.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Amenity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := amenity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Amenity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Amenity.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := amenity.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Amenity.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Amenity.created_at"`)}
	}
	return nil
}

func (_c *AmenityCreate) sqlSave(ctx context.Context) (*Amenity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AmenityCreate) createSpec() (*Amenity, *sqlgraph.CreateSpec) {
	var (
		_node = &Amenity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(amenity.Table, sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(amenity.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(amenity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(amenity.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(amenity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   amenity.PropertiesTable,
			Columns: amenity.PropertiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PropertyAmenitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   amenity.PropertyAmenitiesTable,
			Columns: []string{amenity.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Amenity.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AmenityUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *AmenityCreate) OnConflict(opts ...sql.ConflictOption) *AmenityUpsertOne {
	_c.conflict = opts
	return &AmenityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Amenity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AmenityCreate) OnConflictColumns(columns ...string) *AmenityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AmenityUpsertOne{
		create: _c,
	}
}

type (
	// AmenityUpsertOne is the builder for "upsert"-ing
	//  one Amenity node.
	AmenityUpsertOne struct {
		create *AmenityCreate
	}

	// AmenityUpsert is the "OnConflict" setter.
	AmenityUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *AmenityUpsert) SetCode(v string) *AmenityUpsert {
	u.Set(amenity.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AmenityUpsert) UpdateCode() *AmenityUpsert {
	u.SetExcluded(amenity.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *AmenityUpsert) SetName(v string) *AmenityUpsert {
	u.Set(amenity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AmenityUpsert) UpdateName() *AmenityUpsert {
	u.SetExcluded(amenity.FieldName)
	return u
}

// SetCategory sets the "category" field.
func (u *AmenityUpsert) SetCategory(v string) *AmenityUpsert {
	u.Set(amenity.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *AmenityUpsert) UpdateCategory() *AmenityUpsert {
	u.SetExcluded(amenity.FieldCategory)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AmenityUpsert) SetCreatedAt(v time.Time) *AmenityUpsert {
	u.Set(amenity.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AmenityUpsert) UpdateCreatedAt() *AmenityUpsert {
	u.SetExcluded(amenity.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Amenity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(amenity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AmenityUpsertOne) UpdateNewValues() *AmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(amenity.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Amenity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AmenityUpsertOne) Ignore() *AmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AmenityUpsertOne) DoNothing() *AmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AmenityCreate.OnConflict
// documentation for more info.
func (u *AmenityUpsertOne) Update(set func(*AmenityUpsert)) *AmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AmenityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *AmenityUpsertOne) SetCode(v string) *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AmenityUpsertOne) UpdateCode() *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AmenityUpsertOne) SetName(v string) *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AmenityUpsertOne) UpdateName() *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *AmenityUpsertOne) SetCategory(v string) *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *AmenityUpsertOne) UpdateCategory() *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCategory()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AmenityUpsertOne) SetCreatedAt(v time.Time) *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AmenityUpsertOne) UpdateCreatedAt() *AmenityUpsertOne {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AmenityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AmenityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AmenityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AmenityUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AmenityUpsertOne.ID is not supported by MySQL driver. Use AmenityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AmenityUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AmenityCreateBulk is the builder for creating many Amenity entities in bulk.
type AmenityCreateBulk struct {
	config
	err      error
	builders []*AmenityCreate
	conflict []sql.ConflictOption
}

// Save creates the Amenity entities in the database.
func (_c *AmenityCreateBulk) Save(ctx context.Context) ([]*Amenity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Amenity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AmenityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AmenityCreateBulk) SaveX(ctx context.Context) []*Amenity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AmenityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AmenityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Amenity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AmenityUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *AmenityCreateBulk) OnConflict(opts ...sql.ConflictOption) *AmenityUpsertBulk {
	_c.conflict = opts
	return &AmenityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Amenity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AmenityCreateBulk) OnConflictColumns(columns ...string) *AmenityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AmenityUpsertBulk{
		create: _c,
	}
}

// AmenityUpsertBulk is the builder for "upsert"-ing
// a bulk of Amenity nodes.
type AmenityUpsertBulk struct {
	create *AmenityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Amenity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(amenity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AmenityUpsertBulk) UpdateNewValues() *AmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(amenity.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Amenity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AmenityUpsertBulk) Ignore() *AmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AmenityUpsertBulk) DoNothing() *AmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AmenityCreateBulk.OnConflict
// documentation for more info.
func (u *AmenityUpsertBulk) Update(set func(*AmenityUpsert)) *AmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AmenityUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *AmenityUpsertBulk) SetCode(v string) *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AmenityUpsertBulk) UpdateCode() *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AmenityUpsertBulk) SetName(v string) *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AmenityUpsertBulk) UpdateName() *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateName()
	})
}

// SetCategory sets the "category" field.
func (u *AmenityUpsertBulk) SetCategory(v string) *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *AmenityUpsertBulk) UpdateCategory() *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCategory()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AmenityUpsertBulk) SetCreatedAt(v time.Time) *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AmenityUpsertBulk) UpdateCreatedAt() *AmenityUpsertBulk {
	return u.Update(func(s *AmenityUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *AmenityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AmenityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AmenityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AmenityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
