// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/propertyamenity"
	"github.com/google/uuid"
)

// PropertyAmenity is the model entity for the PropertyAmenity schema.
type PropertyAmenity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID of the property
	PropertyID uuid.UUID `json:"property_id,omitempty"`
	// ID of the amenity
	AmenityID uuid.UUID `json:"amenity_id,omitempty"`
	// Additional amenity details (e.g., {"spaces":2} for parking)
	Details map[string]interface{} `json:"details,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyAmenityQuery when eager-loading is set.
	Edges        PropertyAmenityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PropertyAmenityEdges holds the relations/edges for other nodes in the graph.
type PropertyAmenityEdges struct {
	// The property
	Property *Property `json:"property,omitempty"`
	// The amenity
	Amenity *Amenity `json:"amenity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PropertyOrErr returns the Property value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyAmenityEdges) PropertyOrErr() (*Property, error) {
	if e.Property != nil {
		return e.Property, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: property.Label}
	}
	return nil, &NotLoadedError{edge: "property"}
}

// AmenityOrErr returns the Amenity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyAmenityEdges) AmenityOrErr() (*Amenity, error) {
	if e.Amenity != nil {
		return e.Amenity, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: amenity.Label}
	}
	return nil, &NotLoadedError{edge: "amenity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PropertyAmenity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case propertyamenity.FieldDetails:
			values[i] = new([]byte)
		case propertyamenity.FieldID:
			values[i] = new(sql.NullInt64)
		case propertyamenity.FieldPropertyID, propertyamenity.FieldAmenityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PropertyAmenity fields.
func (_m *PropertyAmenity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case propertyamenity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case propertyamenity.FieldPropertyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field property_id", values[i])
			} else if value != nil {
				_m.PropertyID = *value
			}
		case propertyamenity.FieldAmenityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field amenity_id", values[i])
			} else if value != nil {
				_m.AmenityID = *value
			}
		case propertyamenity.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PropertyAmenity.
// This includes values selected through modifiers, order, etc.
func (_m *PropertyAmenity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProperty queries the "property" edge of the PropertyAmenity entity.
func (_m *PropertyAmenity) QueryProperty() *PropertyQuery {
	return NewPropertyAmenityClient(_m.config).QueryProperty(_m)
}

// QueryAmenity queries the "amenity" edge of the PropertyAmenity entity.
func (_m *PropertyAmenity) QueryAmenity() *AmenityQuery {
	return NewPropertyAmenityClient(_m.config).QueryAmenity(_m)
}

// Update returns a builder for updating this PropertyAmenity.
// Note that you need to call PropertyAmenity.Unwrap() before calling this method if this PropertyAmenity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PropertyAmenity) Update() *PropertyAmenityUpdateOne {
	return NewPropertyAmenityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PropertyAmenity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PropertyAmenity) Unwrap() *PropertyAmenity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PropertyAmenity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PropertyAmenity) String() string {
	var builder strings.Builder
	builder.WriteString("PropertyAmenity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("property_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyID))
	builder.WriteString(", ")
	builder.WriteString("amenity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmenityID))
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteByte(')')
	return builder.String()
}

// PropertyAmenities is a parsable slice of PropertyAmenity.
type PropertyAmenities []*PropertyAmenity
