// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/propertyamenity"
	"github.com/google/uuid"
)

// PropertyAmenityCreate is the builder for creating a PropertyAmenity entity.
type PropertyAmenityCreate struct {
	config
	mutation *PropertyAmenityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPropertyID sets the "property_id" field.
func (_c *PropertyAmenityCreate) SetPropertyID(v uuid.UUID) *PropertyAmenityCreate {
	_c.mutation.SetPropertyID(v)
	return _c
}

// SetAmenityID sets the "amenity_id" field.
func (_c *PropertyAmenityCreate) SetAmenityID(v uuid.UUID) *PropertyAmenityCreate {
	_c.mutation.SetAmenityID(v)
	return _c
}

// SetDetails sets the "details" field.
func (_c *PropertyAmenityCreate) SetDetails(v map[string]interface{}) *PropertyAmenityCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetProperty sets the "property" edge to the Property entity.
func (_c *PropertyAmenityCreate) SetProperty(v *Property) *PropertyAmenityCreate {
	return _c.SetPropertyID(v.ID)
}

// SetAmenity sets the "amenity" edge to the Amenity entity.
func (_c *PropertyAmenityCreate) SetAmenity(v *Amenity) *PropertyAmenityCreate {
	return _c.SetAmenityID(v.ID)
}

// Mutation returns the PropertyAmenityMutation object of the builder.
func (_c *PropertyAmenityCreate) Mutation() *PropertyAmenityMutation {
	return _c.mutation
}

// Save creates the PropertyAmenity in the database.
func (_c *PropertyAmenityCreate) Save(ctx context.Context) (*PropertyAmenity, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PropertyAmenityCreate) SaveX(ctx context.Context) *PropertyAmenity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyAmenityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyAmenityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PropertyAmenityCreate) check() error {
	if _, ok := _c.mutation.PropertyID(); !ok {
		return &ValidationError{Name: "property_id", err: errors.New(`ent: missing required field "PropertyAmenity.property_id"`)}
	}
	if _, ok := _c.mutation.AmenityID(); !ok {
		return &ValidationError{Name: "amenity_id", err: errors.New(`ent: missing required field "PropertyAmenity.amenity_id"`)}
	}
	if len(_c.mutation.PropertyIDs()) == 0 {
		return &ValidationError{Name: "property", err: errors.New(`ent: missing required edge "PropertyAmenity.property"`)}
	}
	if len(_c.mutation.AmenityIDs()) == 0 {
		return &ValidationError{Name: "amenity", err: errors.New(`ent: missing required edge "PropertyAmenity.amenity"`)}
	}
	return nil
}

func (_c *PropertyAmenityCreate) sqlSave(ctx context.Context) (*PropertyAmenity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PropertyAmenityCreate) createSpec() (*PropertyAmenity, *sqlgraph.CreateSpec) {
	var (
		_node = &PropertyAmenity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(propertyamenity.Table, sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(propertyamenity.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if nodes := _c.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   propertyamenity.PropertyTable,
			Columns: []string{propertyamenity.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PropertyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AmenityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   propertyamenity.AmenityTable,
			Columns: []string{propertyamenity.AmenityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AmenityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PropertyAmenity.Create().
//		SetPropertyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PropertyAmenityUpsert) {
//			SetPropertyID(v+v).
//		}).
//		Exec(ctx)
func (_c *PropertyAmenityCreate) OnConflict(opts ...sql.ConflictOption) *PropertyAmenityUpsertOne {
	_c.conflict = opts
	return &PropertyAmenityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PropertyAmenityCreate) OnConflictColumns(columns ...string) *PropertyAmenityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PropertyAmenityUpsertOne{
		create: _c,
	}
}

type (
	// PropertyAmenityUpsertOne is the builder for "upsert"-ing
	//  one PropertyAmenity node.
	PropertyAmenityUpsertOne struct {
		create *PropertyAmenityCreate
	}

	// PropertyAmenityUpsert is the "OnConflict" setter.
	PropertyAmenityUpsert struct {
		*sql.UpdateSet
	}
)

// SetPropertyID sets the "property_id" field.
func (u *PropertyAmenityUpsert) SetPropertyID(v uuid.UUID) *PropertyAmenityUpsert {
	u.Set(propertyamenity.FieldPropertyID, v)
	return u
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsert) UpdatePropertyID() *PropertyAmenityUpsert {
	u.SetExcluded(propertyamenity.FieldPropertyID)
	return u
}

// SetAmenityID sets the "amenity_id" field.
func (u *PropertyAmenityUpsert) SetAmenityID(v uuid.UUID) *PropertyAmenityUpsert {
	u.Set(propertyamenity.FieldAmenityID, v)
	return u
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsert) UpdateAmenityID() *PropertyAmenityUpsert {
	u.SetExcluded(propertyamenity.FieldAmenityID)
	return u
}

// SetDetails sets the "details" field.
func (u *PropertyAmenityUpsert) SetDetails(v map[string]interface{}) *PropertyAmenityUpsert {
	u.Set(propertyamenity.FieldDetails, v)
	return u
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *PropertyAmenityUpsert) UpdateDetails() *PropertyAmenityUpsert {
	u.SetExcluded(propertyamenity.FieldDetails)
	return u
}

// ClearDetails clears the value of the "details" field.
func (u *PropertyAmenityUpsert) ClearDetails() *PropertyAmenityUpsert {
	u.SetNull(propertyamenity.FieldDetails)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PropertyAmenityUpsertOne) UpdateNewValues() *PropertyAmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PropertyAmenityUpsertOne) Ignore() *PropertyAmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PropertyAmenityUpsertOne) DoNothing() *PropertyAmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PropertyAmenityCreate.OnConflict
// documentation for more info.
func (u *PropertyAmenityUpsertOne) Update(set func(*PropertyAmenityUpsert)) *PropertyAmenityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PropertyAmenityUpsert{UpdateSet: update})
	}))
	return u
}

// SetPropertyID sets the "property_id" field.
func (u *PropertyAmenityUpsertOne) SetPropertyID(v uuid.UUID) *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetPropertyID(v)
	})
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsertOne) UpdatePropertyID() *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdatePropertyID()
	})
}

// SetAmenityID sets the "amenity_id" field.
func (u *PropertyAmenityUpsertOne) SetAmenityID(v uuid.UUID) *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetAmenityID(v)
	})
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsertOne) UpdateAmenityID() *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdateAmenityID()
	})
}

// SetDetails sets the "details" field.
func (u *PropertyAmenityUpsertOne) SetDetails(v map[string]interface{}) *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *PropertyAmenityUpsertOne) UpdateDetails() *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdateDetails()
	})
}

// ClearDetails clears the value of the "details" field.
func (u *PropertyAmenityUpsertOne) ClearDetails() *PropertyAmenityUpsertOne {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.ClearDetails()
	})
}

// Exec executes the query.
func (u *PropertyAmenityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PropertyAmenityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PropertyAmenityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PropertyAmenityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PropertyAmenityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PropertyAmenityCreateBulk is the builder for creating many PropertyAmenity entities in bulk.
type PropertyAmenityCreateBulk struct {
	config
	err      error
	builders []*PropertyAmenityCreate
	conflict []sql.ConflictOption
}

// Save creates the PropertyAmenity entities in the database.
func (_c *PropertyAmenityCreateBulk) Save(ctx context.Context) ([]*PropertyAmenity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PropertyAmenity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PropertyAmenityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PropertyAmenityCreateBulk) SaveX(ctx context.Context) []*PropertyAmenity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PropertyAmenityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PropertyAmenityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PropertyAmenity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PropertyAmenityUpsert) {
//			SetPropertyID(v+v).
//		}).
//		Exec(ctx)
func (_c *PropertyAmenityCreateBulk) OnConflict(opts ...sql.ConflictOption) *PropertyAmenityUpsertBulk {
	_c.conflict = opts
	return &PropertyAmenityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PropertyAmenityCreateBulk) OnConflictColumns(columns ...string) *PropertyAmenityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PropertyAmenityUpsertBulk{
		create: _c,
	}
}

// PropertyAmenityUpsertBulk is the builder for "upsert"-ing
// a bulk of PropertyAmenity nodes.
type PropertyAmenityUpsertBulk struct {
	create *PropertyAmenityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PropertyAmenityUpsertBulk) UpdateNewValues() *PropertyAmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PropertyAmenity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PropertyAmenityUpsertBulk) Ignore() *PropertyAmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PropertyAmenityUpsertBulk) DoNothing() *PropertyAmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PropertyAmenityCreateBulk.OnConflict
// documentation for more info.
func (u *PropertyAmenityUpsertBulk) Update(set func(*PropertyAmenityUpsert)) *PropertyAmenityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PropertyAmenityUpsert{UpdateSet: update})
	}))
	return u
}

// SetPropertyID sets the "property_id" field.
func (u *PropertyAmenityUpsertBulk) SetPropertyID(v uuid.UUID) *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetPropertyID(v)
	})
}

// UpdatePropertyID sets the "property_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsertBulk) UpdatePropertyID() *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdatePropertyID()
	})
}

// SetAmenityID sets the "amenity_id" field.
func (u *PropertyAmenityUpsertBulk) SetAmenityID(v uuid.UUID) *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetAmenityID(v)
	})
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *PropertyAmenityUpsertBulk) UpdateAmenityID() *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdateAmenityID()
	})
}

// SetDetails sets the "details" field.
func (u *PropertyAmenityUpsertBulk) SetDetails(v map[string]interface{}) *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *PropertyAmenityUpsertBulk) UpdateDetails() *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.UpdateDetails()
	})
}

// ClearDetails clears the value of the "details" field.
func (u *PropertyAmenityUpsertBulk) ClearDetails() *PropertyAmenityUpsertBulk {
	return u.Update(func(s *PropertyAmenityUpsert) {
		s.ClearDetails()
	})
}

// Exec executes the query.
func (u *PropertyAmenityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PropertyAmenityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PropertyAmenityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PropertyAmenityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
