// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/propertyamenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/room"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/user"
	"github.com/google/uuid"
)

// PropertyUpdate is the builder for updating Property entities.
type PropertyUpdate struct {
	config
	hooks    []Hook
	mutation *PropertyMutation
}

// Where appends a list predicates to the PropertyUpdate builder.
func (_u *PropertyUpdate) Where(ps ...predicate.Property) *PropertyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *PropertyUpdate) SetOwnerID(v uuid.UUID) *PropertyUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableOwnerID(v *uuid.UUID) *PropertyUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PropertyUpdate) SetTitle(v string) *PropertyUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableTitle(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PropertyUpdate) SetType(v property.Type) *PropertyUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableType(v *property.Type) *PropertyUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDescriptionShort sets the "description_short" field.
func (_u *PropertyUpdate) SetDescriptionShort(v string) *PropertyUpdate {
	_u.mutation.SetDescriptionShort(v)
	return _u
}

// SetNillableDescriptionShort sets the "description_short" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableDescriptionShort(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetDescriptionShort(*v)
	}
	return _u
}

// ClearDescriptionShort clears the value of the "description_short" field.
func (_u *PropertyUpdate) ClearDescriptionShort() *PropertyUpdate {
	_u.mutation.ClearDescriptionShort()
	return _u
}

// SetDescriptionLong sets the "description_long" field.
func (_u *PropertyUpdate) SetDescriptionLong(v string) *PropertyUpdate {
	_u.mutation.SetDescriptionLong(v)
	return _u
}

// SetNillableDescriptionLong sets the "description_long" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableDescriptionLong(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetDescriptionLong(*v)
	}
	return _u
}

// ClearDescriptionLong clears the value of the "description_long" field.
func (_u *PropertyUpdate) ClearDescriptionLong() *PropertyUpdate {
	_u.mutation.ClearDescriptionLong()
	return _u
}

// SetMaxGuests sets the "max_guests" field.
func (_u *PropertyUpdate) SetMaxGuests(v int) *PropertyUpdate {
	_u.mutation.ResetMaxGuests()
	_u.mutation.SetMaxGuests(v)
	return _u
}

// SetNillableMaxGuests sets the "max_guests" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableMaxGuests(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetMaxGuests(*v)
	}
	return _u
}

// AddMaxGuests adds value to the "max_guests" field.
func (_u *PropertyUpdate) AddMaxGuests(v int) *PropertyUpdate {
	_u.mutation.AddMaxGuests(v)
	return _u
}

// ClearMaxGuests clears the value of the "max_guests" field.
func (_u *PropertyUpdate) ClearMaxGuests() *PropertyUpdate {
	_u.mutation.ClearMaxGuests()
	return _u
}

// SetBathroomsTotal sets the "bathrooms_total" field.
func (_u *PropertyUpdate) SetBathroomsTotal(v float64) *PropertyUpdate {
	_u.mutation.ResetBathroomsTotal()
	_u.mutation.SetBathroomsTotal(v)
	return _u
}

// SetNillableBathroomsTotal sets the "bathrooms_total" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableBathroomsTotal(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetBathroomsTotal(*v)
	}
	return _u
}

// AddBathroomsTotal adds value to the "bathrooms_total" field.
func (_u *PropertyUpdate) AddBathroomsTotal(v float64) *PropertyUpdate {
	_u.mutation.AddBathroomsTotal(v)
	return _u
}

// ClearBathroomsTotal clears the value of the "bathrooms_total" field.
func (_u *PropertyUpdate) ClearBathroomsTotal() *PropertyUpdate {
	_u.mutation.ClearBathroomsTotal()
	return _u
}

// SetAddressLine1 sets the "address_line1" field.
func (_u *PropertyUpdate) SetAddressLine1(v string) *PropertyUpdate {
	_u.mutation.SetAddressLine1(v)
	return _u
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableAddressLine1(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetAddressLine1(*v)
	}
	return _u
}

// SetAddressLine2 sets the "address_line2" field.
func (_u *PropertyUpdate) SetAddressLine2(v string) *PropertyUpdate {
	_u.mutation.SetAddressLine2(v)
	return _u
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableAddressLine2(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetAddressLine2(*v)
	}
	return _u
}

// ClearAddressLine2 clears the value of the "address_line2" field.
func (_u *PropertyUpdate) ClearAddressLine2() *PropertyUpdate {
	_u.mutation.ClearAddressLine2()
	return _u
}

// SetCity sets the "city" field.
func (_u *PropertyUpdate) SetCity(v string) *PropertyUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCity(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *PropertyUpdate) SetRegion(v string) *PropertyUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableRegion(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *PropertyUpdate) SetPostalCode(v string) *PropertyUpdate {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePostalCode(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *PropertyUpdate) SetCountry(v string) *PropertyUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCountry(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *PropertyUpdate) SetLatitude(v float64) *PropertyUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableLatitude(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *PropertyUpdate) AddLatitude(v float64) *PropertyUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *PropertyUpdate) ClearLatitude() *PropertyUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *PropertyUpdate) SetLongitude(v float64) *PropertyUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableLongitude(v *float64) *PropertyUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *PropertyUpdate) AddLongitude(v float64) *PropertyUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *PropertyUpdate) ClearLongitude() *PropertyUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// SetCheckinTime sets the "checkin_time" field.
func (_u *PropertyUpdate) SetCheckinTime(v time.Time) *PropertyUpdate {
	_u.mutation.SetCheckinTime(v)
	return _u
}

// SetNillableCheckinTime sets the "checkin_time" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCheckinTime(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetCheckinTime(*v)
	}
	return _u
}

// ClearCheckinTime clears the value of the "checkin_time" field.
func (_u *PropertyUpdate) ClearCheckinTime() *PropertyUpdate {
	_u.mutation.ClearCheckinTime()
	return _u
}

// SetCheckoutTime sets the "checkout_time" field.
func (_u *PropertyUpdate) SetCheckoutTime(v time.Time) *PropertyUpdate {
	_u.mutation.SetCheckoutTime(v)
	return _u
}

// SetNillableCheckoutTime sets the "checkout_time" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCheckoutTime(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetCheckoutTime(*v)
	}
	return _u
}

// ClearCheckoutTime clears the value of the "checkout_time" field.
func (_u *PropertyUpdate) ClearCheckoutTime() *PropertyUpdate {
	_u.mutation.ClearCheckoutTime()
	return _u
}

// SetMinNights sets the "min_nights" field.
func (_u *PropertyUpdate) SetMinNights(v int) *PropertyUpdate {
	_u.mutation.ResetMinNights()
	_u.mutation.SetMinNights(v)
	return _u
}

// SetNillableMinNights sets the "min_nights" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableMinNights(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetMinNights(*v)
	}
	return _u
}

// AddMinNights adds value to the "min_nights" field.
func (_u *PropertyUpdate) AddMinNights(v int) *PropertyUpdate {
	_u.mutation.AddMinNights(v)
	return _u
}

// ClearMinNights clears the value of the "min_nights" field.
func (_u *PropertyUpdate) ClearMinNights() *PropertyUpdate {
	_u.mutation.ClearMinNights()
	return _u
}

// SetMaxNights sets the "max_nights" field.
func (_u *PropertyUpdate) SetMaxNights(v int) *PropertyUpdate {
	_u.mutation.ResetMaxNights()
	_u.mutation.SetMaxNights(v)
	return _u
}

// SetNillableMaxNights sets the "max_nights" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableMaxNights(v *int) *PropertyUpdate {
	if v != nil {
		_u.SetMaxNights(*v)
	}
	return _u
}

// AddMaxNights adds value to the "max_nights" field.
func (_u *PropertyUpdate) AddMaxNights(v int) *PropertyUpdate {
	_u.mutation.AddMaxNights(v)
	return _u
}

// ClearMaxNights clears the value of the "max_nights" field.
func (_u *PropertyUpdate) ClearMaxNights() *PropertyUpdate {
	_u.mutation.ClearMaxNights()
	return _u
}

// SetPetsAllowed sets the "pets_allowed" field.
func (_u *PropertyUpdate) SetPetsAllowed(v bool) *PropertyUpdate {
	_u.mutation.SetPetsAllowed(v)
	return _u
}

// SetNillablePetsAllowed sets the "pets_allowed" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillablePetsAllowed(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetPetsAllowed(*v)
	}
	return _u
}

// SetSmokingAllowed sets the "smoking_allowed" field.
func (_u *PropertyUpdate) SetSmokingAllowed(v bool) *PropertyUpdate {
	_u.mutation.SetSmokingAllowed(v)
	return _u
}

// SetNillableSmokingAllowed sets the "smoking_allowed" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableSmokingAllowed(v *bool) *PropertyUpdate {
	if v != nil {
		_u.SetSmokingAllowed(*v)
	}
	return _u
}

// SetHouseRules sets the "house_rules" field.
func (_u *PropertyUpdate) SetHouseRules(v string) *PropertyUpdate {
	_u.mutation.SetHouseRules(v)
	return _u
}

// SetNillableHouseRules sets the "house_rules" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableHouseRules(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetHouseRules(*v)
	}
	return _u
}

// ClearHouseRules clears the value of the "house_rules" field.
func (_u *PropertyUpdate) ClearHouseRules() *PropertyUpdate {
	_u.mutation.ClearHouseRules()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PropertyUpdate) SetStatus(v property.Status) *PropertyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableStatus(v *property.Status) *PropertyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *PropertyUpdate) SetSubmittedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableSubmittedAt(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *PropertyUpdate) ClearSubmittedAt() *PropertyUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *PropertyUpdate) SetReviewedBy(v uuid.UUID) *PropertyUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableReviewedBy(v *uuid.UUID) *PropertyUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *PropertyUpdate) ClearReviewedBy() *PropertyUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *PropertyUpdate) SetReviewedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableReviewedAt(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *PropertyUpdate) ClearReviewedAt() *PropertyUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *PropertyUpdate) SetReviewNotes(v string) *PropertyUpdate {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableReviewNotes(v *string) *PropertyUpdate {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *PropertyUpdate) ClearReviewNotes() *PropertyUpdate {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PropertyUpdate) SetCreatedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PropertyUpdate) SetNillableCreatedAt(v *time.Time) *PropertyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PropertyUpdate) SetUpdatedAt(v time.Time) *PropertyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PropertyUpdate) SetOwner(v *User) *PropertyUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetReviewerID sets the "reviewer" edge to the User entity by ID.
func (_u *PropertyUpdate) SetReviewerID(id uuid.UUID) *PropertyUpdate {
	_u.mutation.SetReviewerID(id)
	return _u
}

// SetNillableReviewerID sets the "reviewer" edge to the User entity by ID if the given value is not nil.
func (_u *PropertyUpdate) SetNillableReviewerID(id *uuid.UUID) *PropertyUpdate {
	if id != nil {
		_u = _u.SetReviewerID(*id)
	}
	return _u
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_u *PropertyUpdate) SetReviewer(v *User) *PropertyUpdate {
	return _u.SetReviewerID(v.ID)
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (_u *PropertyUpdate) AddRoomIDs(ids ...uuid.UUID) *PropertyUpdate {
	_u.mutation.AddRoomIDs(ids...)
	return _u
}

// AddRooms adds the "rooms" edges to the Room entity.
func (_u *PropertyUpdate) AddRooms(v ...*Room) *PropertyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoomIDs(ids...)
}

// AddAmenityIDs adds the "amenities" edge to the Amenity entity by IDs.
func (_u *PropertyUpdate) AddAmenityIDs(ids ...uuid.UUID) *PropertyUpdate {
	_u.mutation.AddAmenityIDs(ids...)
	return _u
}

// AddAmenities adds the "amenities" edges to the Amenity entity.
func (_u *PropertyUpdate) AddAmenities(v ...*Amenity) *PropertyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAmenityIDs(ids...)
}

// AddPropertyAmenityIDs adds the "property_amenities" edge to the PropertyAmenity entity by IDs.
func (_u *PropertyUpdate) AddPropertyAmenityIDs(ids ...int) *PropertyUpdate {
	_u.mutation.AddPropertyAmenityIDs(ids...)
	return _u
}

// AddPropertyAmenities adds the "property_amenities" edges to the PropertyAmenity entity.
func (_u *PropertyUpdate) AddPropertyAmenities(v ...*PropertyAmenity) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyAmenityIDs(ids...)
}

// Mutation returns the PropertyMutation object of the builder.
func (_u *PropertyUpdate) Mutation() *PropertyMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PropertyUpdate) ClearOwner() *PropertyUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the User entity.
func (_u *PropertyUpdate) ClearReviewer() *PropertyUpdate {
	_u.mutation.ClearReviewer()
	return _u
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (_u *PropertyUpdate) ClearRooms() *PropertyUpdate {
	_u.mutation.ClearRooms()
	return _u
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (_u *PropertyUpdate) RemoveRoomIDs(ids ...uuid.UUID) *PropertyUpdate {
	_u.mutation.RemoveRoomIDs(ids...)
	return _u
}

// RemoveRooms removes "rooms" edges to Room entities.
func (_u *PropertyUpdate) RemoveRooms(v ...*Room) *PropertyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoomIDs(ids...)
}

// ClearAmenities clears all "amenities" edges to the Amenity entity.
func (_u *PropertyUpdate) ClearAmenities() *PropertyUpdate {
	_u.mutation.ClearAmenities()
	return _u
}

// RemoveAmenityIDs removes the "amenities" edge to Amenity entities by IDs.
func (_u *PropertyUpdate) RemoveAmenityIDs(ids ...uuid.UUID) *PropertyUpdate {
	_u.mutation.RemoveAmenityIDs(ids...)
	return _u
}

// RemoveAmenities removes "amenities" edges to Amenity entities.
func (_u *PropertyUpdate) RemoveAmenities(v ...*Amenity) *PropertyUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAmenityIDs(ids...)
}

// ClearPropertyAmenities clears all "property_amenities" edges to the PropertyAmenity entity.
func (_u *PropertyUpdate) ClearPropertyAmenities() *PropertyUpdate {
	_u.mutation.ClearPropertyAmenities()
	return _u
}

// RemovePropertyAmenityIDs removes the "property_amenities" edge to PropertyAmenity entities by IDs.
func (_u *PropertyUpdate) RemovePropertyAmenityIDs(ids ...int) *PropertyUpdate {
	_u.mutation.RemovePropertyAmenityIDs(ids...)
	return _u
}

// RemovePropertyAmenities removes "property_amenities" edges to PropertyAmenity entities.
func (_u *PropertyUpdate) RemovePropertyAmenities(v ...*PropertyAmenity) *PropertyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyAmenityIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PropertyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PropertyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PropertyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PropertyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PropertyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := property.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PropertyUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := property.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Property.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := property.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Property.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxGuests(); ok {
		if err := property.MaxGuestsValidator(v); err != nil {
			return &ValidationError{Name: "max_guests", err: fmt.Errorf(`ent: validator failed for field "Property.max_guests": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BathroomsTotal(); ok {
		if err := property.BathroomsTotalValidator(v); err != nil {
			return &ValidationError{Name: "bathrooms_total", err: fmt.Errorf(`ent: validator failed for field "Property.bathrooms_total": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AddressLine1(); ok {
		if err := property.AddressLine1Validator(v); err != nil {
			return &ValidationError{Name: "address_line1", err: fmt.Errorf(`ent: validator failed for field "Property.address_line1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := property.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Property.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := property.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Property.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := property.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Property.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := property.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Property.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinNights(); ok {
		if err := property.MinNightsValidator(v); err != nil {
			return &ValidationError{Name: "min_nights", err: fmt.Errorf(`ent: validator failed for field "Property.min_nights": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxNights(); ok {
		if err := property.MaxNightsValidator(v); err != nil {
			return &ValidationError{Name: "max_nights", err: fmt.Errorf(`ent: validator failed for field "Property.max_nights": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := property.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Property.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Property.owner"`)
	}
	return nil
}

func (_u *PropertyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(property.Table, property.Columns, sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(property.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(property.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DescriptionShort(); ok {
		_spec.SetField(property.FieldDescriptionShort, field.TypeString, value)
	}
	if _u.mutation.DescriptionShortCleared() {
		_spec.ClearField(property.FieldDescriptionShort, field.TypeString)
	}
	if value, ok := _u.mutation.DescriptionLong(); ok {
		_spec.SetField(property.FieldDescriptionLong, field.TypeString, value)
	}
	if _u.mutation.DescriptionLongCleared() {
		_spec.ClearField(property.FieldDescriptionLong, field.TypeString)
	}
	if value, ok := _u.mutation.MaxGuests(); ok {
		_spec.SetField(property.FieldMaxGuests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxGuests(); ok {
		_spec.AddField(property.FieldMaxGuests, field.TypeInt, value)
	}
	if _u.mutation.MaxGuestsCleared() {
		_spec.ClearField(property.FieldMaxGuests, field.TypeInt)
	}
	if value, ok := _u.mutation.BathroomsTotal(); ok {
		_spec.SetField(property.FieldBathroomsTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBathroomsTotal(); ok {
		_spec.AddField(property.FieldBathroomsTotal, field.TypeFloat64, value)
	}
	if _u.mutation.BathroomsTotalCleared() {
		_spec.ClearField(property.FieldBathroomsTotal, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AddressLine1(); ok {
		_spec.SetField(property.FieldAddressLine1, field.TypeString, value)
	}
	if value, ok := _u.mutation.AddressLine2(); ok {
		_spec.SetField(property.FieldAddressLine2, field.TypeString, value)
	}
	if _u.mutation.AddressLine2Cleared() {
		_spec.ClearField(property.FieldAddressLine2, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(property.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(property.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(property.FieldPostalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(property.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(property.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(property.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CheckinTime(); ok {
		_spec.SetField(property.FieldCheckinTime, field.TypeTime, value)
	}
	if _u.mutation.CheckinTimeCleared() {
		_spec.ClearField(property.FieldCheckinTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CheckoutTime(); ok {
		_spec.SetField(property.FieldCheckoutTime, field.TypeTime, value)
	}
	if _u.mutation.CheckoutTimeCleared() {
		_spec.ClearField(property.FieldCheckoutTime, field.TypeTime)
	}
	if value, ok := _u.mutation.MinNights(); ok {
		_spec.SetField(property.FieldMinNights, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinNights(); ok {
		_spec.AddField(property.FieldMinNights, field.TypeInt, value)
	}
	if _u.mutation.MinNightsCleared() {
		_spec.ClearField(property.FieldMinNights, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxNights(); ok {
		_spec.SetField(property.FieldMaxNights, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxNights(); ok {
		_spec.AddField(property.FieldMaxNights, field.TypeInt, value)
	}
	if _u.mutation.MaxNightsCleared() {
		_spec.ClearField(property.FieldMaxNights, field.TypeInt)
	}
	if value, ok := _u.mutation.PetsAllowed(); ok {
		_spec.SetField(property.FieldPetsAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SmokingAllowed(); ok {
		_spec.SetField(property.FieldSmokingAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HouseRules(); ok {
		_spec.SetField(property.FieldHouseRules, field.TypeString, value)
	}
	if _u.mutation.HouseRulesCleared() {
		_spec.ClearField(property.FieldHouseRules, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(property.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(property.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(property.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(property.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(property.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(property.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(property.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(property.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(property.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.OwnerTable,
			Columns: []string{property.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.OwnerTable,
			Columns: []string{property.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   property.ReviewerTable,
			Columns: []string{property.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   property.ReviewerTable,
			Columns: []string{property.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !_u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAmenitiesIDs(); len(nodes) > 0 && !_u.mutation.AmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AmenitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertyAmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertyAmenitiesIDs(); len(nodes) > 0 && !_u.mutation.PropertyAmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertyAmenitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{property.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PropertyUpdateOne is the builder for updating a single Property entity.
type PropertyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PropertyMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *PropertyUpdateOne) SetOwnerID(v uuid.UUID) *PropertyUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableOwnerID(v *uuid.UUID) *PropertyUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PropertyUpdateOne) SetTitle(v string) *PropertyUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableTitle(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PropertyUpdateOne) SetType(v property.Type) *PropertyUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableType(v *property.Type) *PropertyUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDescriptionShort sets the "description_short" field.
func (_u *PropertyUpdateOne) SetDescriptionShort(v string) *PropertyUpdateOne {
	_u.mutation.SetDescriptionShort(v)
	return _u
}

// SetNillableDescriptionShort sets the "description_short" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableDescriptionShort(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetDescriptionShort(*v)
	}
	return _u
}

// ClearDescriptionShort clears the value of the "description_short" field.
func (_u *PropertyUpdateOne) ClearDescriptionShort() *PropertyUpdateOne {
	_u.mutation.ClearDescriptionShort()
	return _u
}

// SetDescriptionLong sets the "description_long" field.
func (_u *PropertyUpdateOne) SetDescriptionLong(v string) *PropertyUpdateOne {
	_u.mutation.SetDescriptionLong(v)
	return _u
}

// SetNillableDescriptionLong sets the "description_long" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableDescriptionLong(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetDescriptionLong(*v)
	}
	return _u
}

// ClearDescriptionLong clears the value of the "description_long" field.
func (_u *PropertyUpdateOne) ClearDescriptionLong() *PropertyUpdateOne {
	_u.mutation.ClearDescriptionLong()
	return _u
}

// SetMaxGuests sets the "max_guests" field.
func (_u *PropertyUpdateOne) SetMaxGuests(v int) *PropertyUpdateOne {
	_u.mutation.ResetMaxGuests()
	_u.mutation.SetMaxGuests(v)
	return _u
}

// SetNillableMaxGuests sets the "max_guests" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableMaxGuests(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetMaxGuests(*v)
	}
	return _u
}

// AddMaxGuests adds value to the "max_guests" field.
func (_u *PropertyUpdateOne) AddMaxGuests(v int) *PropertyUpdateOne {
	_u.mutation.AddMaxGuests(v)
	return _u
}

// ClearMaxGuests clears the value of the "max_guests" field.
func (_u *PropertyUpdateOne) ClearMaxGuests() *PropertyUpdateOne {
	_u.mutation.ClearMaxGuests()
	return _u
}

// SetBathroomsTotal sets the "bathrooms_total" field.
func (_u *PropertyUpdateOne) SetBathroomsTotal(v float64) *PropertyUpdateOne {
	_u.mutation.ResetBathroomsTotal()
	_u.mutation.SetBathroomsTotal(v)
	return _u
}

// SetNillableBathroomsTotal sets the "bathrooms_total" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableBathroomsTotal(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetBathroomsTotal(*v)
	}
	return _u
}

// AddBathroomsTotal adds value to the "bathrooms_total" field.
func (_u *PropertyUpdateOne) AddBathroomsTotal(v float64) *PropertyUpdateOne {
	_u.mutation.AddBathroomsTotal(v)
	return _u
}

// ClearBathroomsTotal clears the value of the "bathrooms_total" field.
func (_u *PropertyUpdateOne) ClearBathroomsTotal() *PropertyUpdateOne {
	_u.mutation.ClearBathroomsTotal()
	return _u
}

// SetAddressLine1 sets the "address_line1" field.
func (_u *PropertyUpdateOne) SetAddressLine1(v string) *PropertyUpdateOne {
	_u.mutation.SetAddressLine1(v)
	return _u
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableAddressLine1(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetAddressLine1(*v)
	}
	return _u
}

// SetAddressLine2 sets the "address_line2" field.
func (_u *PropertyUpdateOne) SetAddressLine2(v string) *PropertyUpdateOne {
	_u.mutation.SetAddressLine2(v)
	return _u
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableAddressLine2(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetAddressLine2(*v)
	}
	return _u
}

// ClearAddressLine2 clears the value of the "address_line2" field.
func (_u *PropertyUpdateOne) ClearAddressLine2() *PropertyUpdateOne {
	_u.mutation.ClearAddressLine2()
	return _u
}

// SetCity sets the "city" field.
func (_u *PropertyUpdateOne) SetCity(v string) *PropertyUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCity(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *PropertyUpdateOne) SetRegion(v string) *PropertyUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableRegion(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *PropertyUpdateOne) SetPostalCode(v string) *PropertyUpdateOne {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePostalCode(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *PropertyUpdateOne) SetCountry(v string) *PropertyUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCountry(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *PropertyUpdateOne) SetLatitude(v float64) *PropertyUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableLatitude(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *PropertyUpdateOne) AddLatitude(v float64) *PropertyUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *PropertyUpdateOne) ClearLatitude() *PropertyUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *PropertyUpdateOne) SetLongitude(v float64) *PropertyUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableLongitude(v *float64) *PropertyUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *PropertyUpdateOne) AddLongitude(v float64) *PropertyUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *PropertyUpdateOne) ClearLongitude() *PropertyUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// SetCheckinTime sets the "checkin_time" field.
func (_u *PropertyUpdateOne) SetCheckinTime(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetCheckinTime(v)
	return _u
}

// SetNillableCheckinTime sets the "checkin_time" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCheckinTime(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetCheckinTime(*v)
	}
	return _u
}

// ClearCheckinTime clears the value of the "checkin_time" field.
func (_u *PropertyUpdateOne) ClearCheckinTime() *PropertyUpdateOne {
	_u.mutation.ClearCheckinTime()
	return _u
}

// SetCheckoutTime sets the "checkout_time" field.
func (_u *PropertyUpdateOne) SetCheckoutTime(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetCheckoutTime(v)
	return _u
}

// SetNillableCheckoutTime sets the "checkout_time" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCheckoutTime(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetCheckoutTime(*v)
	}
	return _u
}

// ClearCheckoutTime clears the value of the "checkout_time" field.
func (_u *PropertyUpdateOne) ClearCheckoutTime() *PropertyUpdateOne {
	_u.mutation.ClearCheckoutTime()
	return _u
}

// SetMinNights sets the "min_nights" field.
func (_u *PropertyUpdateOne) SetMinNights(v int) *PropertyUpdateOne {
	_u.mutation.ResetMinNights()
	_u.mutation.SetMinNights(v)
	return _u
}

// SetNillableMinNights sets the "min_nights" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableMinNights(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetMinNights(*v)
	}
	return _u
}

// AddMinNights adds value to the "min_nights" field.
func (_u *PropertyUpdateOne) AddMinNights(v int) *PropertyUpdateOne {
	_u.mutation.AddMinNights(v)
	return _u
}

// ClearMinNights clears the value of the "min_nights" field.
func (_u *PropertyUpdateOne) ClearMinNights() *PropertyUpdateOne {
	_u.mutation.ClearMinNights()
	return _u
}

// SetMaxNights sets the "max_nights" field.
func (_u *PropertyUpdateOne) SetMaxNights(v int) *PropertyUpdateOne {
	_u.mutation.ResetMaxNights()
	_u.mutation.SetMaxNights(v)
	return _u
}

// SetNillableMaxNights sets the "max_nights" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableMaxNights(v *int) *PropertyUpdateOne {
	if v != nil {
		_u.SetMaxNights(*v)
	}
	return _u
}

// AddMaxNights adds value to the "max_nights" field.
func (_u *PropertyUpdateOne) AddMaxNights(v int) *PropertyUpdateOne {
	_u.mutation.AddMaxNights(v)
	return _u
}

// ClearMaxNights clears the value of the "max_nights" field.
func (_u *PropertyUpdateOne) ClearMaxNights() *PropertyUpdateOne {
	_u.mutation.ClearMaxNights()
	return _u
}

// SetPetsAllowed sets the "pets_allowed" field.
func (_u *PropertyUpdateOne) SetPetsAllowed(v bool) *PropertyUpdateOne {
	_u.mutation.SetPetsAllowed(v)
	return _u
}

// SetNillablePetsAllowed sets the "pets_allowed" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillablePetsAllowed(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetPetsAllowed(*v)
	}
	return _u
}

// SetSmokingAllowed sets the "smoking_allowed" field.
func (_u *PropertyUpdateOne) SetSmokingAllowed(v bool) *PropertyUpdateOne {
	_u.mutation.SetSmokingAllowed(v)
	return _u
}

// SetNillableSmokingAllowed sets the "smoking_allowed" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableSmokingAllowed(v *bool) *PropertyUpdateOne {
	if v != nil {
		_u.SetSmokingAllowed(*v)
	}
	return _u
}

// SetHouseRules sets the "house_rules" field.
func (_u *PropertyUpdateOne) SetHouseRules(v string) *PropertyUpdateOne {
	_u.mutation.SetHouseRules(v)
	return _u
}

// SetNillableHouseRules sets the "house_rules" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableHouseRules(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetHouseRules(*v)
	}
	return _u
}

// ClearHouseRules clears the value of the "house_rules" field.
func (_u *PropertyUpdateOne) ClearHouseRules() *PropertyUpdateOne {
	_u.mutation.ClearHouseRules()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PropertyUpdateOne) SetStatus(v property.Status) *PropertyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableStatus(v *property.Status) *PropertyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *PropertyUpdateOne) SetSubmittedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableSubmittedAt(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *PropertyUpdateOne) ClearSubmittedAt() *PropertyUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *PropertyUpdateOne) SetReviewedBy(v uuid.UUID) *PropertyUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableReviewedBy(v *uuid.UUID) *PropertyUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *PropertyUpdateOne) ClearReviewedBy() *PropertyUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *PropertyUpdateOne) SetReviewedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableReviewedAt(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *PropertyUpdateOne) ClearReviewedAt() *PropertyUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *PropertyUpdateOne) SetReviewNotes(v string) *PropertyUpdateOne {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableReviewNotes(v *string) *PropertyUpdateOne {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *PropertyUpdateOne) ClearReviewNotes() *PropertyUpdateOne {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PropertyUpdateOne) SetCreatedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableCreatedAt(v *time.Time) *PropertyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PropertyUpdateOne) SetUpdatedAt(v time.Time) *PropertyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PropertyUpdateOne) SetOwner(v *User) *PropertyUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetReviewerID sets the "reviewer" edge to the User entity by ID.
func (_u *PropertyUpdateOne) SetReviewerID(id uuid.UUID) *PropertyUpdateOne {
	_u.mutation.SetReviewerID(id)
	return _u
}

// SetNillableReviewerID sets the "reviewer" edge to the User entity by ID if the given value is not nil.
func (_u *PropertyUpdateOne) SetNillableReviewerID(id *uuid.UUID) *PropertyUpdateOne {
	if id != nil {
		_u = _u.SetReviewerID(*id)
	}
	return _u
}

// SetReviewer sets the "reviewer" edge to the User entity.
func (_u *PropertyUpdateOne) SetReviewer(v *User) *PropertyUpdateOne {
	return _u.SetReviewerID(v.ID)
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (_u *PropertyUpdateOne) AddRoomIDs(ids ...uuid.UUID) *PropertyUpdateOne {
	_u.mutation.AddRoomIDs(ids...)
	return _u
}

// AddRooms adds the "rooms" edges to the Room entity.
func (_u *PropertyUpdateOne) AddRooms(v ...*Room) *PropertyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoomIDs(ids...)
}

// AddAmenityIDs adds the "amenities" edge to the Amenity entity by IDs.
func (_u *PropertyUpdateOne) AddAmenityIDs(ids ...uuid.UUID) *PropertyUpdateOne {
	_u.mutation.AddAmenityIDs(ids...)
	return _u
}

// AddAmenities adds the "amenities" edges to the Amenity entity.
func (_u *PropertyUpdateOne) AddAmenities(v ...*Amenity) *PropertyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAmenityIDs(ids...)
}

// AddPropertyAmenityIDs adds the "property_amenities" edge to the PropertyAmenity entity by IDs.
func (_u *PropertyUpdateOne) AddPropertyAmenityIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.AddPropertyAmenityIDs(ids...)
	return _u
}

// AddPropertyAmenities adds the "property_amenities" edges to the PropertyAmenity entity.
func (_u *PropertyUpdateOne) AddPropertyAmenities(v ...*PropertyAmenity) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPropertyAmenityIDs(ids...)
}

// Mutation returns the PropertyMutation object of the builder.
func (_u *PropertyUpdateOne) Mutation() *PropertyMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PropertyUpdateOne) ClearOwner() *PropertyUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearReviewer clears the "reviewer" edge to the User entity.
func (_u *PropertyUpdateOne) ClearReviewer() *PropertyUpdateOne {
	_u.mutation.ClearReviewer()
	return _u
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (_u *PropertyUpdateOne) ClearRooms() *PropertyUpdateOne {
	_u.mutation.ClearRooms()
	return _u
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (_u *PropertyUpdateOne) RemoveRoomIDs(ids ...uuid.UUID) *PropertyUpdateOne {
	_u.mutation.RemoveRoomIDs(ids...)
	return _u
}

// RemoveRooms removes "rooms" edges to Room entities.
func (_u *PropertyUpdateOne) RemoveRooms(v ...*Room) *PropertyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoomIDs(ids...)
}

// ClearAmenities clears all "amenities" edges to the Amenity entity.
func (_u *PropertyUpdateOne) ClearAmenities() *PropertyUpdateOne {
	_u.mutation.ClearAmenities()
	return _u
}

// RemoveAmenityIDs removes the "amenities" edge to Amenity entities by IDs.
func (_u *PropertyUpdateOne) RemoveAmenityIDs(ids ...uuid.UUID) *PropertyUpdateOne {
	_u.mutation.RemoveAmenityIDs(ids...)
	return _u
}

// RemoveAmenities removes "amenities" edges to Amenity entities.
func (_u *PropertyUpdateOne) RemoveAmenities(v ...*Amenity) *PropertyUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAmenityIDs(ids...)
}

// ClearPropertyAmenities clears all "property_amenities" edges to the PropertyAmenity entity.
func (_u *PropertyUpdateOne) ClearPropertyAmenities() *PropertyUpdateOne {
	_u.mutation.ClearPropertyAmenities()
	return _u
}

// RemovePropertyAmenityIDs removes the "property_amenities" edge to PropertyAmenity entities by IDs.
func (_u *PropertyUpdateOne) RemovePropertyAmenityIDs(ids ...int) *PropertyUpdateOne {
	_u.mutation.RemovePropertyAmenityIDs(ids...)
	return _u
}

// RemovePropertyAmenities removes "property_amenities" edges to PropertyAmenity entities.
func (_u *PropertyUpdateOne) RemovePropertyAmenities(v ...*PropertyAmenity) *PropertyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePropertyAmenityIDs(ids...)
}

// Where appends a list predicates to the PropertyUpdate builder.
func (_u *PropertyUpdateOne) Where(ps ...predicate.Property) *PropertyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PropertyUpdateOne) Select(field string, fields ...string) *PropertyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Property entity.
func (_u *PropertyUpdateOne) Save(ctx context.Context) (*Property, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PropertyUpdateOne) SaveX(ctx context.Context) *Property {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PropertyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PropertyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PropertyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := property.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PropertyUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := property.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Property.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := property.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Property.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxGuests(); ok {
		if err := property.MaxGuestsValidator(v); err != nil {
			return &ValidationError{Name: "max_guests", err: fmt.Errorf(`ent: validator failed for field "Property.max_guests": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BathroomsTotal(); ok {
		if err := property.BathroomsTotalValidator(v); err != nil {
			return &ValidationError{Name: "bathrooms_total", err: fmt.Errorf(`ent: validator failed for field "Property.bathrooms_total": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AddressLine1(); ok {
		if err := property.AddressLine1Validator(v); err != nil {
			return &ValidationError{Name: "address_line1", err: fmt.Errorf(`ent: validator failed for field "Property.address_line1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := property.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Property.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := property.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Property.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := property.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Property.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := property.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Property.country": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MinNights(); ok {
		if err := property.MinNightsValidator(v); err != nil {
			return &ValidationError{Name: "min_nights", err: fmt.Errorf(`ent: validator failed for field "Property.min_nights": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxNights(); ok {
		if err := property.MaxNightsValidator(v); err != nil {
			return &ValidationError{Name: "max_nights", err: fmt.Errorf(`ent: validator failed for field "Property.max_nights": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := property.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Property.status": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Property.owner"`)
	}
	return nil
}

func (_u *PropertyUpdateOne) sqlSave(ctx context.Context) (_node *Property, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(property.Table, property.Columns, sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Property.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, property.FieldID)
		for _, f := range fields {
			if !property.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != property.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(property.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(property.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DescriptionShort(); ok {
		_spec.SetField(property.FieldDescriptionShort, field.TypeString, value)
	}
	if _u.mutation.DescriptionShortCleared() {
		_spec.ClearField(property.FieldDescriptionShort, field.TypeString)
	}
	if value, ok := _u.mutation.DescriptionLong(); ok {
		_spec.SetField(property.FieldDescriptionLong, field.TypeString, value)
	}
	if _u.mutation.DescriptionLongCleared() {
		_spec.ClearField(property.FieldDescriptionLong, field.TypeString)
	}
	if value, ok := _u.mutation.MaxGuests(); ok {
		_spec.SetField(property.FieldMaxGuests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxGuests(); ok {
		_spec.AddField(property.FieldMaxGuests, field.TypeInt, value)
	}
	if _u.mutation.MaxGuestsCleared() {
		_spec.ClearField(property.FieldMaxGuests, field.TypeInt)
	}
	if value, ok := _u.mutation.BathroomsTotal(); ok {
		_spec.SetField(property.FieldBathroomsTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBathroomsTotal(); ok {
		_spec.AddField(property.FieldBathroomsTotal, field.TypeFloat64, value)
	}
	if _u.mutation.BathroomsTotalCleared() {
		_spec.ClearField(property.FieldBathroomsTotal, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AddressLine1(); ok {
		_spec.SetField(property.FieldAddressLine1, field.TypeString, value)
	}
	if value, ok := _u.mutation.AddressLine2(); ok {
		_spec.SetField(property.FieldAddressLine2, field.TypeString, value)
	}
	if _u.mutation.AddressLine2Cleared() {
		_spec.ClearField(property.FieldAddressLine2, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(property.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(property.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(property.FieldPostalCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(property.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(property.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(property.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(property.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(property.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CheckinTime(); ok {
		_spec.SetField(property.FieldCheckinTime, field.TypeTime, value)
	}
	if _u.mutation.CheckinTimeCleared() {
		_spec.ClearField(property.FieldCheckinTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CheckoutTime(); ok {
		_spec.SetField(property.FieldCheckoutTime, field.TypeTime, value)
	}
	if _u.mutation.CheckoutTimeCleared() {
		_spec.ClearField(property.FieldCheckoutTime, field.TypeTime)
	}
	if value, ok := _u.mutation.MinNights(); ok {
		_spec.SetField(property.FieldMinNights, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinNights(); ok {
		_spec.AddField(property.FieldMinNights, field.TypeInt, value)
	}
	if _u.mutation.MinNightsCleared() {
		_spec.ClearField(property.FieldMinNights, field.TypeInt)
	}
	if value, ok := _u.mutation.MaxNights(); ok {
		_spec.SetField(property.FieldMaxNights, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxNights(); ok {
		_spec.AddField(property.FieldMaxNights, field.TypeInt, value)
	}
	if _u.mutation.MaxNightsCleared() {
		_spec.ClearField(property.FieldMaxNights, field.TypeInt)
	}
	if value, ok := _u.mutation.PetsAllowed(); ok {
		_spec.SetField(property.FieldPetsAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SmokingAllowed(); ok {
		_spec.SetField(property.FieldSmokingAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.HouseRules(); ok {
		_spec.SetField(property.FieldHouseRules, field.TypeString, value)
	}
	if _u.mutation.HouseRulesCleared() {
		_spec.ClearField(property.FieldHouseRules, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(property.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(property.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(property.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(property.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(property.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(property.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(property.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(property.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(property.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.OwnerTable,
			Columns: []string{property.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   property.OwnerTable,
			Columns: []string{property.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   property.ReviewerTable,
			Columns: []string{property.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   property.ReviewerTable,
			Columns: []string{property.ReviewerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !_u.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   property.RoomsTable,
			Columns: []string{property.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAmenitiesIDs(); len(nodes) > 0 && !_u.mutation.AmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AmenitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   property.AmenitiesTable,
			Columns: property.AmenitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(amenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PropertyAmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPropertyAmenitiesIDs(); len(nodes) > 0 && !_u.mutation.PropertyAmenitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertyAmenitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   property.PropertyAmenitiesTable,
			Columns: []string{property.PropertyAmenitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Property{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{property.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
