// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/user"
	"github.com/google/uuid"
)

// Property is the model entity for the Property schema.
type Property struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ID of the property owner
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Property title
	Title string `json:"title,omitempty"`
	// Type of property
	Type property.Type `json:"type,omitempty"`
	// Short description of the property
	DescriptionShort string `json:"description_short,omitempty"`
	// Long description of the property
	DescriptionLong string `json:"description_long,omitempty"`
	// Maximum number of guests
	MaxGuests int `json:"max_guests,omitempty"`
	// Total number of bathrooms
	BathroomsTotal float64 `json:"bathrooms_total,omitempty"`
	// Primary address line
	AddressLine1 string `json:"address_line1,omitempty"`
	// Secondary address line
	AddressLine2 string `json:"address_line2,omitempty"`
	// City
	City string `json:"city,omitempty"`
	// State/province/region
	Region string `json:"region,omitempty"`
	// Postal/ZIP code
	PostalCode string `json:"postal_code,omitempty"`
	// Country
	Country string `json:"country,omitempty"`
	// Latitude coordinate
	Latitude float64 `json:"latitude,omitempty"`
	// Longitude coordinate
	Longitude float64 `json:"longitude,omitempty"`
	// Check-in time
	CheckinTime time.Time `json:"checkin_time,omitempty"`
	// Check-out time
	CheckoutTime time.Time `json:"checkout_time,omitempty"`
	// Minimum number of nights
	MinNights int `json:"min_nights,omitempty"`
	// Maximum number of nights
	MaxNights int `json:"max_nights,omitempty"`
	// Whether pets are allowed
	PetsAllowed bool `json:"pets_allowed,omitempty"`
	// Whether smoking is allowed
	SmokingAllowed bool `json:"smoking_allowed,omitempty"`
	// House rules
	HouseRules string `json:"house_rules,omitempty"`
	// Property status
	Status property.Status `json:"status,omitempty"`
	// When the property was submitted for review
	SubmittedAt time.Time `json:"submitted_at,omitempty"`
	// ID of the user who reviewed the property
	ReviewedBy uuid.UUID `json:"reviewed_by,omitempty"`
	// When the property was reviewed
	ReviewedAt time.Time `json:"reviewed_at,omitempty"`
	// Notes from the review
	ReviewNotes string `json:"review_notes,omitempty"`
	// When the property was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the property was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PropertyQuery when eager-loading is set.
	Edges        PropertyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PropertyEdges holds the relations/edges for other nodes in the graph.
type PropertyEdges struct {
	// Property owner
	Owner *User `json:"owner,omitempty"`
	// User who reviewed this property
	Reviewer *User `json:"reviewer,omitempty"`
	// Rooms in this property
	Rooms []*Room `json:"rooms,omitempty"`
	// Amenities available at this property
	Amenities []*Amenity `json:"amenities,omitempty"`
	// PropertyAmenities holds the value of the property_amenities edge.
	PropertyAmenities []*PropertyAmenity `json:"property_amenities,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ReviewerOrErr returns the Reviewer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PropertyEdges) ReviewerOrErr() (*User, error) {
	if e.Reviewer != nil {
		return e.Reviewer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reviewer"}
}

// RoomsOrErr returns the Rooms value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyEdges) RoomsOrErr() ([]*Room, error) {
	if e.loadedTypes[2] {
		return e.Rooms, nil
	}
	return nil, &NotLoadedError{edge: "rooms"}
}

// AmenitiesOrErr returns the Amenities value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyEdges) AmenitiesOrErr() ([]*Amenity, error) {
	if e.loadedTypes[3] {
		return e.Amenities, nil
	}
	return nil, &NotLoadedError{edge: "amenities"}
}

// PropertyAmenitiesOrErr returns the PropertyAmenities value or an error if the edge
// was not loaded in eager-loading.
func (e PropertyEdges) PropertyAmenitiesOrErr() ([]*PropertyAmenity, error) {
	if e.loadedTypes[4] {
		return e.PropertyAmenities, nil
	}
	return nil, &NotLoadedError{edge: "property_amenities"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Property) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case property.FieldPetsAllowed, property.FieldSmokingAllowed:
			values[i] = new(sql.NullBool)
		case property.FieldBathroomsTotal, property.FieldLatitude, property.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case property.FieldMaxGuests, property.FieldMinNights, property.FieldMaxNights:
			values[i] = new(sql.NullInt64)
		case property.FieldTitle, property.FieldType, property.FieldDescriptionShort, property.FieldDescriptionLong, property.FieldAddressLine1, property.FieldAddressLine2, property.FieldCity, property.FieldRegion, property.FieldPostalCode, property.FieldCountry, property.FieldHouseRules, property.FieldStatus, property.FieldReviewNotes:
			values[i] = new(sql.NullString)
		case property.FieldCheckinTime, property.FieldCheckoutTime, property.FieldSubmittedAt, property.FieldReviewedAt, property.FieldCreatedAt, property.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case property.FieldID, property.FieldOwnerID, property.FieldReviewedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Property fields.
func (_m *Property) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case property.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case property.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				_m.OwnerID = *value
			}
		case property.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case property.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = property.Type(value.String)
			}
		case property.FieldDescriptionShort:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_short", values[i])
			} else if value.Valid {
				_m.DescriptionShort = value.String
			}
		case property.FieldDescriptionLong:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_long", values[i])
			} else if value.Valid {
				_m.DescriptionLong = value.String
			}
		case property.FieldMaxGuests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_guests", values[i])
			} else if value.Valid {
				_m.MaxGuests = int(value.Int64)
			}
		case property.FieldBathroomsTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bathrooms_total", values[i])
			} else if value.Valid {
				_m.BathroomsTotal = value.Float64
			}
		case property.FieldAddressLine1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_line1", values[i])
			} else if value.Valid {
				_m.AddressLine1 = value.String
			}
		case property.FieldAddressLine2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address_line2", values[i])
			} else if value.Valid {
				_m.AddressLine2 = value.String
			}
		case property.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = value.String
			}
		case property.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case property.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				_m.PostalCode = value.String
			}
		case property.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case property.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = value.Float64
			}
		case property.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = value.Float64
			}
		case property.FieldCheckinTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_time", values[i])
			} else if value.Valid {
				_m.CheckinTime = value.Time
			}
		case property.FieldCheckoutTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_time", values[i])
			} else if value.Valid {
				_m.CheckoutTime = value.Time
			}
		case property.FieldMinNights:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_nights", values[i])
			} else if value.Valid {
				_m.MinNights = int(value.Int64)
			}
		case property.FieldMaxNights:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_nights", values[i])
			} else if value.Valid {
				_m.MaxNights = int(value.Int64)
			}
		case property.FieldPetsAllowed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pets_allowed", values[i])
			} else if value.Valid {
				_m.PetsAllowed = value.Bool
			}
		case property.FieldSmokingAllowed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field smoking_allowed", values[i])
			} else if value.Valid {
				_m.SmokingAllowed = value.Bool
			}
		case property.FieldHouseRules:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field house_rules", values[i])
			} else if value.Valid {
				_m.HouseRules = value.String
			}
		case property.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = property.Status(value.String)
			}
		case property.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = value.Time
			}
		case property.FieldReviewedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value != nil {
				_m.ReviewedBy = *value
			}
		case property.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = value.Time
			}
		case property.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				_m.ReviewNotes = value.String
			}
		case property.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case property.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Property.
// This includes values selected through modifiers, order, etc.
func (_m *Property) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Property entity.
func (_m *Property) QueryOwner() *UserQuery {
	return NewPropertyClient(_m.config).QueryOwner(_m)
}

// QueryReviewer queries the "reviewer" edge of the Property entity.
func (_m *Property) QueryReviewer() *UserQuery {
	return NewPropertyClient(_m.config).QueryReviewer(_m)
}

// QueryRooms queries the "rooms" edge of the Property entity.
func (_m *Property) QueryRooms() *RoomQuery {
	return NewPropertyClient(_m.config).QueryRooms(_m)
}

// QueryAmenities queries the "amenities" edge of the Property entity.
func (_m *Property) QueryAmenities() *AmenityQuery {
	return NewPropertyClient(_m.config).QueryAmenities(_m)
}

// QueryPropertyAmenities queries the "property_amenities" edge of the Property entity.
func (_m *Property) QueryPropertyAmenities() *PropertyAmenityQuery {
	return NewPropertyClient(_m.config).QueryPropertyAmenities(_m)
}

// Update returns a builder for updating this Property.
// Note that you need to call Property.Unwrap() before calling this method if this Property
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Property) Update() *PropertyUpdateOne {
	return NewPropertyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Property entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Property) Unwrap() *Property {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Property is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Property) String() string {
	var builder strings.Builder
	builder.WriteString("Property(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("description_short=")
	builder.WriteString(_m.DescriptionShort)
	builder.WriteString(", ")
	builder.WriteString("description_long=")
	builder.WriteString(_m.DescriptionLong)
	builder.WriteString(", ")
	builder.WriteString("max_guests=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxGuests))
	builder.WriteString(", ")
	builder.WriteString("bathrooms_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.BathroomsTotal))
	builder.WriteString(", ")
	builder.WriteString("address_line1=")
	builder.WriteString(_m.AddressLine1)
	builder.WriteString(", ")
	builder.WriteString("address_line2=")
	builder.WriteString(_m.AddressLine2)
	builder.WriteString(", ")
	builder.WriteString("city=")
	builder.WriteString(_m.City)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("postal_code=")
	builder.WriteString(_m.PostalCode)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("latitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Latitude))
	builder.WriteString(", ")
	builder.WriteString("longitude=")
	builder.WriteString(fmt.Sprintf("%v", _m.Longitude))
	builder.WriteString(", ")
	builder.WriteString("checkin_time=")
	builder.WriteString(_m.CheckinTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("checkout_time=")
	builder.WriteString(_m.CheckoutTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("min_nights=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinNights))
	builder.WriteString(", ")
	builder.WriteString("max_nights=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxNights))
	builder.WriteString(", ")
	builder.WriteString("pets_allowed=")
	builder.WriteString(fmt.Sprintf("%v", _m.PetsAllowed))
	builder.WriteString(", ")
	builder.WriteString("smoking_allowed=")
	builder.WriteString(fmt.Sprintf("%v", _m.SmokingAllowed))
	builder.WriteString(", ")
	builder.WriteString("house_rules=")
	builder.WriteString(_m.HouseRules)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(_m.SubmittedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reviewed_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewedBy))
	builder.WriteString(", ")
	builder.WriteString("reviewed_at=")
	builder.WriteString(_m.ReviewedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("review_notes=")
	builder.WriteString(_m.ReviewNotes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Properties is a parsable slice of Property.
type Properties []*Property
