// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/propertyamenity"
	"github.com/google/uuid"
)

// PropertyAmenityQuery is the builder for querying PropertyAmenity entities.
type PropertyAmenityQuery struct {
	config
	ctx          *QueryContext
	order        []propertyamenity.OrderOption
	inters       []Interceptor
	predicates   []predicate.PropertyAmenity
	withProperty *PropertyQuery
	withAmenity  *AmenityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PropertyAmenityQuery builder.
func (_q *PropertyAmenityQuery) Where(ps ...predicate.PropertyAmenity) *PropertyAmenityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PropertyAmenityQuery) Limit(limit int) *PropertyAmenityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PropertyAmenityQuery) Offset(offset int) *PropertyAmenityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PropertyAmenityQuery) Unique(unique bool) *PropertyAmenityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PropertyAmenityQuery) Order(o ...propertyamenity.OrderOption) *PropertyAmenityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProperty chains the current query on the "property" edge.
func (_q *PropertyAmenityQuery) QueryProperty() *PropertyQuery {
	query := (&PropertyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(propertyamenity.Table, propertyamenity.FieldID, selector),
			sqlgraph.To(property.Table, property.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, propertyamenity.PropertyTable, propertyamenity.PropertyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAmenity chains the current query on the "amenity" edge.
func (_q *PropertyAmenityQuery) QueryAmenity() *AmenityQuery {
	query := (&AmenityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(propertyamenity.Table, propertyamenity.FieldID, selector),
			sqlgraph.To(amenity.Table, amenity.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, propertyamenity.AmenityTable, propertyamenity.AmenityColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PropertyAmenity entity from the query.
// Returns a *NotFoundError when no PropertyAmenity was found.
func (_q *PropertyAmenityQuery) First(ctx context.Context) (*PropertyAmenity, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{propertyamenity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PropertyAmenityQuery) FirstX(ctx context.Context) *PropertyAmenity {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PropertyAmenity ID from the query.
// Returns a *NotFoundError when no PropertyAmenity ID was found.
func (_q *PropertyAmenityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{propertyamenity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PropertyAmenityQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PropertyAmenity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PropertyAmenity entity is found.
// Returns a *NotFoundError when no PropertyAmenity entities are found.
func (_q *PropertyAmenityQuery) Only(ctx context.Context) (*PropertyAmenity, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{propertyamenity.Label}
	default:
		return nil, &NotSingularError{propertyamenity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PropertyAmenityQuery) OnlyX(ctx context.Context) *PropertyAmenity {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PropertyAmenity ID in the query.
// Returns a *NotSingularError when more than one PropertyAmenity ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PropertyAmenityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{propertyamenity.Label}
	default:
		err = &NotSingularError{propertyamenity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PropertyAmenityQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PropertyAmenities.
func (_q *PropertyAmenityQuery) All(ctx context.Context) ([]*PropertyAmenity, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PropertyAmenity, *PropertyAmenityQuery]()
	return withInterceptors[[]*PropertyAmenity](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PropertyAmenityQuery) AllX(ctx context.Context) []*PropertyAmenity {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PropertyAmenity IDs.
func (_q *PropertyAmenityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(propertyamenity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PropertyAmenityQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PropertyAmenityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PropertyAmenityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PropertyAmenityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PropertyAmenityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PropertyAmenityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PropertyAmenityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PropertyAmenityQuery) Clone() *PropertyAmenityQuery {
	if _q == nil {
		return nil
	}
	return &PropertyAmenityQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]propertyamenity.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.PropertyAmenity{}, _q.predicates...),
		withProperty: _q.withProperty.Clone(),
		withAmenity:  _q.withAmenity.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProperty tells the query-builder to eager-load the nodes that are connected to
// the "property" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PropertyAmenityQuery) WithProperty(opts ...func(*PropertyQuery)) *PropertyAmenityQuery {
	query := (&PropertyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProperty = query
	return _q
}

// WithAmenity tells the query-builder to eager-load the nodes that are connected to
// the "amenity" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PropertyAmenityQuery) WithAmenity(opts ...func(*AmenityQuery)) *PropertyAmenityQuery {
	query := (&AmenityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAmenity = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PropertyID uuid.UUID `json:"property_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PropertyAmenity.Query().
//		GroupBy(propertyamenity.FieldPropertyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PropertyAmenityQuery) GroupBy(field string, fields ...string) *PropertyAmenityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PropertyAmenityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = propertyamenity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PropertyID uuid.UUID `json:"property_id,omitempty"`
//	}
//
//	client.PropertyAmenity.Query().
//		Select(propertyamenity.FieldPropertyID).
//		Scan(ctx, &v)
func (_q *PropertyAmenityQuery) Select(fields ...string) *PropertyAmenitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PropertyAmenitySelect{PropertyAmenityQuery: _q}
	sbuild.label = propertyamenity.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PropertyAmenitySelect configured with the given aggregations.
func (_q *PropertyAmenityQuery) Aggregate(fns ...AggregateFunc) *PropertyAmenitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PropertyAmenityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !propertyamenity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PropertyAmenityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PropertyAmenity, error) {
	var (
		nodes       = []*PropertyAmenity{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProperty != nil,
			_q.withAmenity != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PropertyAmenity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PropertyAmenity{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProperty; query != nil {
		if err := _q.loadProperty(ctx, query, nodes, nil,
			func(n *PropertyAmenity, e *Property) { n.Edges.Property = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAmenity; query != nil {
		if err := _q.loadAmenity(ctx, query, nodes, nil,
			func(n *PropertyAmenity, e *Amenity) { n.Edges.Amenity = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PropertyAmenityQuery) loadProperty(ctx context.Context, query *PropertyQuery, nodes []*PropertyAmenity, init func(*PropertyAmenity), assign func(*PropertyAmenity, *Property)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PropertyAmenity)
	for i := range nodes {
		fk := nodes[i].PropertyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(property.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "property_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PropertyAmenityQuery) loadAmenity(ctx context.Context, query *AmenityQuery, nodes []*PropertyAmenity, init func(*PropertyAmenity), assign func(*PropertyAmenity, *Amenity)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PropertyAmenity)
	for i := range nodes {
		fk := nodes[i].AmenityID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(amenity.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "amenity_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PropertyAmenityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PropertyAmenityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(propertyamenity.Table, propertyamenity.Columns, sqlgraph.NewFieldSpec(propertyamenity.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, propertyamenity.FieldID)
		for i := range fields {
			if fields[i] != propertyamenity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProperty != nil {
			_spec.Node.AddColumnOnce(propertyamenity.FieldPropertyID)
		}
		if _q.withAmenity != nil {
			_spec.Node.AddColumnOnce(propertyamenity.FieldAmenityID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PropertyAmenityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(propertyamenity.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = propertyamenity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PropertyAmenityGroupBy is the group-by builder for PropertyAmenity entities.
type PropertyAmenityGroupBy struct {
	selector
	build *PropertyAmenityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PropertyAmenityGroupBy) Aggregate(fns ...AggregateFunc) *PropertyAmenityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PropertyAmenityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyAmenityQuery, *PropertyAmenityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PropertyAmenityGroupBy) sqlScan(ctx context.Context, root *PropertyAmenityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PropertyAmenitySelect is the builder for selecting fields of PropertyAmenity entities.
type PropertyAmenitySelect struct {
	*PropertyAmenityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PropertyAmenitySelect) Aggregate(fns ...AggregateFunc) *PropertyAmenitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PropertyAmenitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PropertyAmenityQuery, *PropertyAmenitySelect](ctx, _s.PropertyAmenityQuery, _s, _s.inters, v)
}

func (_s *PropertyAmenitySelect) sqlScan(ctx context.Context, root *PropertyAmenityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
