// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/room"
	"github.com/google/uuid"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPropertyID sets the "property_id" field.
func (_u *RoomUpdate) SetPropertyID(v uuid.UUID) *RoomUpdate {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *RoomUpdate) SetNillablePropertyID(v *uuid.UUID) *RoomUpdate {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoomUpdate) SetName(v string) *RoomUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableName(v *string) *RoomUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFloorLabel sets the "floor_label" field.
func (_u *RoomUpdate) SetFloorLabel(v string) *RoomUpdate {
	_u.mutation.SetFloorLabel(v)
	return _u
}

// SetNillableFloorLabel sets the "floor_label" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableFloorLabel(v *string) *RoomUpdate {
	if v != nil {
		_u.SetFloorLabel(*v)
	}
	return _u
}

// ClearFloorLabel clears the value of the "floor_label" field.
func (_u *RoomUpdate) ClearFloorLabel() *RoomUpdate {
	_u.mutation.ClearFloorLabel()
	return _u
}

// SetAreaSqFt sets the "area_sq_ft" field.
func (_u *RoomUpdate) SetAreaSqFt(v int) *RoomUpdate {
	_u.mutation.ResetAreaSqFt()
	_u.mutation.SetAreaSqFt(v)
	return _u
}

// SetNillableAreaSqFt sets the "area_sq_ft" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableAreaSqFt(v *int) *RoomUpdate {
	if v != nil {
		_u.SetAreaSqFt(*v)
	}
	return _u
}

// AddAreaSqFt adds value to the "area_sq_ft" field.
func (_u *RoomUpdate) AddAreaSqFt(v int) *RoomUpdate {
	_u.mutation.AddAreaSqFt(v)
	return _u
}

// ClearAreaSqFt clears the value of the "area_sq_ft" field.
func (_u *RoomUpdate) ClearAreaSqFt() *RoomUpdate {
	_u.mutation.ClearAreaSqFt()
	return _u
}

// SetBedMix sets the "bed_mix" field.
func (_u *RoomUpdate) SetBedMix(v map[string]int) *RoomUpdate {
	_u.mutation.SetBedMix(v)
	return _u
}

// SetEnsuiteBath sets the "ensuite_bath" field.
func (_u *RoomUpdate) SetEnsuiteBath(v bool) *RoomUpdate {
	_u.mutation.SetEnsuiteBath(v)
	return _u
}

// SetNillableEnsuiteBath sets the "ensuite_bath" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableEnsuiteBath(v *bool) *RoomUpdate {
	if v != nil {
		_u.SetEnsuiteBath(*v)
	}
	return _u
}

// ClearEnsuiteBath clears the value of the "ensuite_bath" field.
func (_u *RoomUpdate) ClearEnsuiteBath() *RoomUpdate {
	_u.mutation.ClearEnsuiteBath()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RoomUpdate) SetNotes(v string) *RoomUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableNotes(v *string) *RoomUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RoomUpdate) ClearNotes() *RoomUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RoomUpdate) SetCreatedAt(v time.Time) *RoomUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RoomUpdate) SetNillableCreatedAt(v *time.Time) *RoomUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoomUpdate) SetUpdatedAt(v time.Time) *RoomUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProperty sets the "property" edge to the Property entity.
func (_u *RoomUpdate) SetProperty(v *Property) *RoomUpdate {
	return _u.SetPropertyID(v.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdate) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearProperty clears the "property" edge to the Property entity.
func (_u *RoomUpdate) ClearProperty() *RoomUpdate {
	_u.mutation.ClearProperty()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoomUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoomUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoomUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := room.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := room.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Room.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AreaSqFt(); ok {
		if err := room.AreaSqFtValidator(v); err != nil {
			return &ValidationError{Name: "area_sq_ft", err: fmt.Errorf(`ent: validator failed for field "Room.area_sq_ft": %w`, err)}
		}
	}
	if _u.mutation.PropertyCleared() && len(_u.mutation.PropertyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.property"`)
	}
	return nil
}

func (_u *RoomUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(room.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FloorLabel(); ok {
		_spec.SetField(room.FieldFloorLabel, field.TypeString, value)
	}
	if _u.mutation.FloorLabelCleared() {
		_spec.ClearField(room.FieldFloorLabel, field.TypeString)
	}
	if value, ok := _u.mutation.AreaSqFt(); ok {
		_spec.SetField(room.FieldAreaSqFt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAreaSqFt(); ok {
		_spec.AddField(room.FieldAreaSqFt, field.TypeInt, value)
	}
	if _u.mutation.AreaSqFtCleared() {
		_spec.ClearField(room.FieldAreaSqFt, field.TypeInt)
	}
	if value, ok := _u.mutation.BedMix(); ok {
		_spec.SetField(room.FieldBedMix, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.EnsuiteBath(); ok {
		_spec.SetField(room.FieldEnsuiteBath, field.TypeBool, value)
	}
	if _u.mutation.EnsuiteBathCleared() {
		_spec.ClearField(room.FieldEnsuiteBath, field.TypeBool)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(room.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(room.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(room.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(room.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PropertyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PropertyTable,
			Columns: []string{room.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PropertyTable,
			Columns: []string{room.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoomMutation
}

// SetPropertyID sets the "property_id" field.
func (_u *RoomUpdateOne) SetPropertyID(v uuid.UUID) *RoomUpdateOne {
	_u.mutation.SetPropertyID(v)
	return _u
}

// SetNillablePropertyID sets the "property_id" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillablePropertyID(v *uuid.UUID) *RoomUpdateOne {
	if v != nil {
		_u.SetPropertyID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoomUpdateOne) SetName(v string) *RoomUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableName(v *string) *RoomUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFloorLabel sets the "floor_label" field.
func (_u *RoomUpdateOne) SetFloorLabel(v string) *RoomUpdateOne {
	_u.mutation.SetFloorLabel(v)
	return _u
}

// SetNillableFloorLabel sets the "floor_label" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableFloorLabel(v *string) *RoomUpdateOne {
	if v != nil {
		_u.SetFloorLabel(*v)
	}
	return _u
}

// ClearFloorLabel clears the value of the "floor_label" field.
func (_u *RoomUpdateOne) ClearFloorLabel() *RoomUpdateOne {
	_u.mutation.ClearFloorLabel()
	return _u
}

// SetAreaSqFt sets the "area_sq_ft" field.
func (_u *RoomUpdateOne) SetAreaSqFt(v int) *RoomUpdateOne {
	_u.mutation.ResetAreaSqFt()
	_u.mutation.SetAreaSqFt(v)
	return _u
}

// SetNillableAreaSqFt sets the "area_sq_ft" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableAreaSqFt(v *int) *RoomUpdateOne {
	if v != nil {
		_u.SetAreaSqFt(*v)
	}
	return _u
}

// AddAreaSqFt adds value to the "area_sq_ft" field.
func (_u *RoomUpdateOne) AddAreaSqFt(v int) *RoomUpdateOne {
	_u.mutation.AddAreaSqFt(v)
	return _u
}

// ClearAreaSqFt clears the value of the "area_sq_ft" field.
func (_u *RoomUpdateOne) ClearAreaSqFt() *RoomUpdateOne {
	_u.mutation.ClearAreaSqFt()
	return _u
}

// SetBedMix sets the "bed_mix" field.
func (_u *RoomUpdateOne) SetBedMix(v map[string]int) *RoomUpdateOne {
	_u.mutation.SetBedMix(v)
	return _u
}

// SetEnsuiteBath sets the "ensuite_bath" field.
func (_u *RoomUpdateOne) SetEnsuiteBath(v bool) *RoomUpdateOne {
	_u.mutation.SetEnsuiteBath(v)
	return _u
}

// SetNillableEnsuiteBath sets the "ensuite_bath" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableEnsuiteBath(v *bool) *RoomUpdateOne {
	if v != nil {
		_u.SetEnsuiteBath(*v)
	}
	return _u
}

// ClearEnsuiteBath clears the value of the "ensuite_bath" field.
func (_u *RoomUpdateOne) ClearEnsuiteBath() *RoomUpdateOne {
	_u.mutation.ClearEnsuiteBath()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RoomUpdateOne) SetNotes(v string) *RoomUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableNotes(v *string) *RoomUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RoomUpdateOne) ClearNotes() *RoomUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RoomUpdateOne) SetCreatedAt(v time.Time) *RoomUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RoomUpdateOne) SetNillableCreatedAt(v *time.Time) *RoomUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoomUpdateOne) SetUpdatedAt(v time.Time) *RoomUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProperty sets the "property" edge to the Property entity.
func (_u *RoomUpdateOne) SetProperty(v *Property) *RoomUpdateOne {
	return _u.SetPropertyID(v.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (_u *RoomUpdateOne) Mutation() *RoomMutation {
	return _u.mutation
}

// ClearProperty clears the "property" edge to the Property entity.
func (_u *RoomUpdateOne) ClearProperty() *RoomUpdateOne {
	_u.mutation.ClearProperty()
	return _u
}

// Where appends a list predicates to the RoomUpdate builder.
func (_u *RoomUpdateOne) Where(ps ...predicate.Room) *RoomUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoomUpdateOne) Select(field string, fields ...string) *RoomUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Room entity.
func (_u *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoomUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := room.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoomUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := room.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Room.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AreaSqFt(); ok {
		if err := room.AreaSqFtValidator(v); err != nil {
			return &ValidationError{Name: "area_sq_ft", err: fmt.Errorf(`ent: validator failed for field "Room.area_sq_ft": %w`, err)}
		}
	}
	if _u.mutation.PropertyCleared() && len(_u.mutation.PropertyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Room.property"`)
	}
	return nil
}

func (_u *RoomUpdateOne) sqlSave(ctx context.Context) (_node *Room, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Room.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, room.FieldID)
		for _, f := range fields {
			if !room.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != room.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(room.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FloorLabel(); ok {
		_spec.SetField(room.FieldFloorLabel, field.TypeString, value)
	}
	if _u.mutation.FloorLabelCleared() {
		_spec.ClearField(room.FieldFloorLabel, field.TypeString)
	}
	if value, ok := _u.mutation.AreaSqFt(); ok {
		_spec.SetField(room.FieldAreaSqFt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAreaSqFt(); ok {
		_spec.AddField(room.FieldAreaSqFt, field.TypeInt, value)
	}
	if _u.mutation.AreaSqFtCleared() {
		_spec.ClearField(room.FieldAreaSqFt, field.TypeInt)
	}
	if value, ok := _u.mutation.BedMix(); ok {
		_spec.SetField(room.FieldBedMix, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.EnsuiteBath(); ok {
		_spec.SetField(room.FieldEnsuiteBath, field.TypeBool, value)
	}
	if _u.mutation.EnsuiteBathCleared() {
		_spec.ClearField(room.FieldEnsuiteBath, field.TypeBool)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(room.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(room.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(room.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(room.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.PropertyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PropertyTable,
			Columns: []string{room.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.PropertyTable,
			Columns: []string{room.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Room{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
