// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/room"
	"github.com/google/uuid"
)

// Room is the model entity for the Room schema.
type Room struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ID of the property this room belongs to
	PropertyID uuid.UUID `json:"property_id,omitempty"`
	// Room name (e.g., 'Living Room', 'Bedroom 1')
	Name string `json:"name,omitempty"`
	// Floor label (e.g., '1st', 'Garden', 'Loft')
	FloorLabel string `json:"floor_label,omitempty"`
	// Room area in square feet
	AreaSqFt int `json:"area_sq_ft,omitempty"`
	// Bed configuration as JSON (e.g., {"king":1,"queen":1,"twin":0})
	BedMix map[string]int `json:"bed_mix,omitempty"`
	// Whether the room has an ensuite bathroom
	EnsuiteBath bool `json:"ensuite_bath,omitempty"`
	// Additional room notes
	Notes string `json:"notes,omitempty"`
	// When the room was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When the room was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoomQuery when eager-loading is set.
	Edges        RoomEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RoomEdges holds the relations/edges for other nodes in the graph.
type RoomEdges struct {
	// Property this room belongs to
	Property *Property `json:"property,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PropertyOrErr returns the Property value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoomEdges) PropertyOrErr() (*Property, error) {
	if e.Property != nil {
		return e.Property, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: property.Label}
	}
	return nil, &NotLoadedError{edge: "property"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Room) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case room.FieldBedMix:
			values[i] = new([]byte)
		case room.FieldEnsuiteBath:
			values[i] = new(sql.NullBool)
		case room.FieldAreaSqFt:
			values[i] = new(sql.NullInt64)
		case room.FieldName, room.FieldFloorLabel, room.FieldNotes:
			values[i] = new(sql.NullString)
		case room.FieldCreatedAt, room.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case room.FieldID, room.FieldPropertyID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Room fields.
func (_m *Room) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case room.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case room.FieldPropertyID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field property_id", values[i])
			} else if value != nil {
				_m.PropertyID = *value
			}
		case room.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case room.FieldFloorLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field floor_label", values[i])
			} else if value.Valid {
				_m.FloorLabel = value.String
			}
		case room.FieldAreaSqFt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field area_sq_ft", values[i])
			} else if value.Valid {
				_m.AreaSqFt = int(value.Int64)
			}
		case room.FieldBedMix:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field bed_mix", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BedMix); err != nil {
					return fmt.Errorf("unmarshal field bed_mix: %w", err)
				}
			}
		case room.FieldEnsuiteBath:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ensuite_bath", values[i])
			} else if value.Valid {
				_m.EnsuiteBath = value.Bool
			}
		case room.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case room.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case room.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Room.
// This includes values selected through modifiers, order, etc.
func (_m *Room) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProperty queries the "property" edge of the Room entity.
func (_m *Room) QueryProperty() *PropertyQuery {
	return NewRoomClient(_m.config).QueryProperty(_m)
}

// Update returns a builder for updating this Room.
// Note that you need to call Room.Unwrap() before calling this method if this Room
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Room) Update() *RoomUpdateOne {
	return NewRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Room entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Room) Unwrap() *Room {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Room is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Room) String() string {
	var builder strings.Builder
	builder.WriteString("Room(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("property_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertyID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("floor_label=")
	builder.WriteString(_m.FloorLabel)
	builder.WriteString(", ")
	builder.WriteString("area_sq_ft=")
	builder.WriteString(fmt.Sprintf("%v", _m.AreaSqFt))
	builder.WriteString(", ")
	builder.WriteString("bed_mix=")
	builder.WriteString(fmt.Sprintf("%v", _m.BedMix))
	builder.WriteString(", ")
	builder.WriteString("ensuite_bath=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnsuiteBath))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rooms is a parsable slice of Room.
type Rooms []*Room
