// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/evolve-interviews/paxtonedgar-case-study/ent/amenity"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/property"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/room"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/schema"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	amenityFields := schema.Amenity{}.Fields()
	_ = amenityFields
	// amenityDescCode is the schema descriptor for code field.
	amenityDescCode := amenityFields[1].Descriptor()
	// amenity.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	amenity.CodeValidator = amenityDescCode.Validators[0].(func(string) error)
	// amenityDescName is the schema descriptor for name field.
	amenityDescName := amenityFields[2].Descriptor()
	// amenity.NameValidator is a validator for the "name" field. It is called by the builders before save.
	amenity.NameValidator = amenityDescName.Validators[0].(func(string) error)
	// amenityDescCategory is the schema descriptor for category field.
	amenityDescCategory := amenityFields[3].Descriptor()
	// amenity.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	amenity.CategoryValidator = amenityDescCategory.Validators[0].(func(string) error)
	// amenityDescCreatedAt is the schema descriptor for created_at field.
	amenityDescCreatedAt := amenityFields[4].Descriptor()
	// amenity.DefaultCreatedAt holds the default value on creation for the created_at field.
	amenity.DefaultCreatedAt = amenityDescCreatedAt.Default.(func() time.Time)
	// amenityDescID is the schema descriptor for id field.
	amenityDescID := amenityFields[0].Descriptor()
	// amenity.DefaultID holds the default value on creation for the id field.
	amenity.DefaultID = amenityDescID.Default.(func() uuid.UUID)
	propertyFields := schema.Property{}.Fields()
	_ = propertyFields
	// propertyDescTitle is the schema descriptor for title field.
	propertyDescTitle := propertyFields[2].Descriptor()
	// property.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	property.TitleValidator = propertyDescTitle.Validators[0].(func(string) error)
	// propertyDescMaxGuests is the schema descriptor for max_guests field.
	propertyDescMaxGuests := propertyFields[6].Descriptor()
	// property.MaxGuestsValidator is a validator for the "max_guests" field. It is called by the builders before save.
	property.MaxGuestsValidator = propertyDescMaxGuests.Validators[0].(func(int) error)
	// propertyDescBathroomsTotal is the schema descriptor for bathrooms_total field.
	propertyDescBathroomsTotal := propertyFields[7].Descriptor()
	// property.BathroomsTotalValidator is a validator for the "bathrooms_total" field. It is called by the builders before save.
	property.BathroomsTotalValidator = propertyDescBathroomsTotal.Validators[0].(func(float64) error)
	// propertyDescAddressLine1 is the schema descriptor for address_line1 field.
	propertyDescAddressLine1 := propertyFields[8].Descriptor()
	// property.AddressLine1Validator is a validator for the "address_line1" field. It is called by the builders before save.
	property.AddressLine1Validator = propertyDescAddressLine1.Validators[0].(func(string) error)
	// propertyDescCity is the schema descriptor for city field.
	propertyDescCity := propertyFields[10].Descriptor()
	// property.CityValidator is a validator for the "city" field. It is called by the builders before save.
	property.CityValidator = propertyDescCity.Validators[0].(func(string) error)
	// propertyDescRegion is the schema descriptor for region field.
	propertyDescRegion := propertyFields[11].Descriptor()
	// property.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	property.RegionValidator = propertyDescRegion.Validators[0].(func(string) error)
	// propertyDescPostalCode is the schema descriptor for postal_code field.
	propertyDescPostalCode := propertyFields[12].Descriptor()
	// property.PostalCodeValidator is a validator for the "postal_code" field. It is called by the builders before save.
	property.PostalCodeValidator = propertyDescPostalCode.Validators[0].(func(string) error)
	// propertyDescCountry is the schema descriptor for country field.
	propertyDescCountry := propertyFields[13].Descriptor()
	// property.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	property.CountryValidator = propertyDescCountry.Validators[0].(func(string) error)
	// propertyDescMinNights is the schema descriptor for min_nights field.
	propertyDescMinNights := propertyFields[18].Descriptor()
	// property.MinNightsValidator is a validator for the "min_nights" field. It is called by the builders before save.
	property.MinNightsValidator = propertyDescMinNights.Validators[0].(func(int) error)
	// propertyDescMaxNights is the schema descriptor for max_nights field.
	propertyDescMaxNights := propertyFields[19].Descriptor()
	// property.MaxNightsValidator is a validator for the "max_nights" field. It is called by the builders before save.
	property.MaxNightsValidator = propertyDescMaxNights.Validators[0].(func(int) error)
	// propertyDescPetsAllowed is the schema descriptor for pets_allowed field.
	propertyDescPetsAllowed := propertyFields[20].Descriptor()
	// property.DefaultPetsAllowed holds the default value on creation for the pets_allowed field.
	property.DefaultPetsAllowed = propertyDescPetsAllowed.Default.(bool)
	// propertyDescSmokingAllowed is the schema descriptor for smoking_allowed field.
	propertyDescSmokingAllowed := propertyFields[21].Descriptor()
	// property.DefaultSmokingAllowed holds the default value on creation for the smoking_allowed field.
	property.DefaultSmokingAllowed = propertyDescSmokingAllowed.Default.(bool)
	// propertyDescCreatedAt is the schema descriptor for created_at field.
	propertyDescCreatedAt := propertyFields[28].Descriptor()
	// property.DefaultCreatedAt holds the default value on creation for the created_at field.
	property.DefaultCreatedAt = propertyDescCreatedAt.Default.(func() time.Time)
	// propertyDescUpdatedAt is the schema descriptor for updated_at field.
	propertyDescUpdatedAt := propertyFields[29].Descriptor()
	// property.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	property.DefaultUpdatedAt = propertyDescUpdatedAt.Default.(func() time.Time)
	// property.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	property.UpdateDefaultUpdatedAt = propertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// propertyDescID is the schema descriptor for id field.
	propertyDescID := propertyFields[0].Descriptor()
	// property.DefaultID holds the default value on creation for the id field.
	property.DefaultID = propertyDescID.Default.(func() uuid.UUID)
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[2].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = roomDescName.Validators[0].(func(string) error)
	// roomDescAreaSqFt is the schema descriptor for area_sq_ft field.
	roomDescAreaSqFt := roomFields[4].Descriptor()
	// room.AreaSqFtValidator is a validator for the "area_sq_ft" field. It is called by the builders before save.
	room.AreaSqFtValidator = roomDescAreaSqFt.Validators[0].(func(int) error)
	// roomDescBedMix is the schema descriptor for bed_mix field.
	roomDescBedMix := roomFields[5].Descriptor()
	// room.DefaultBedMix holds the default value on creation for the bed_mix field.
	room.DefaultBedMix = roomDescBedMix.Default.(map[string]int)
	// roomDescCreatedAt is the schema descriptor for created_at field.
	roomDescCreatedAt := roomFields[8].Descriptor()
	// room.DefaultCreatedAt holds the default value on creation for the created_at field.
	room.DefaultCreatedAt = roomDescCreatedAt.Default.(func() time.Time)
	// roomDescUpdatedAt is the schema descriptor for updated_at field.
	roomDescUpdatedAt := roomFields[9].Descriptor()
	// room.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	room.DefaultUpdatedAt = roomDescUpdatedAt.Default.(func() time.Time)
	// room.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	room.UpdateDefaultUpdatedAt = roomDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roomDescID is the schema descriptor for id field.
	roomDescID := roomFields[0].Descriptor()
	// room.DefaultID holds the default value on creation for the id field.
	room.DefaultID = roomDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[2].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
