// Code generated by ent, DO NOT EDIT.

package property

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldOwnerID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTitle, v))
}

// DescriptionShort applies equality check predicate on the "description_short" field. It's identical to DescriptionShortEQ.
func DescriptionShort(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldDescriptionShort, v))
}

// DescriptionLong applies equality check predicate on the "description_long" field. It's identical to DescriptionLongEQ.
func DescriptionLong(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldDescriptionLong, v))
}

// MaxGuests applies equality check predicate on the "max_guests" field. It's identical to MaxGuestsEQ.
func MaxGuests(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMaxGuests, v))
}

// BathroomsTotal applies equality check predicate on the "bathrooms_total" field. It's identical to BathroomsTotalEQ.
func BathroomsTotal(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldBathroomsTotal, v))
}

// AddressLine1 applies equality check predicate on the "address_line1" field. It's identical to AddressLine1EQ.
func AddressLine1(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine2 applies equality check predicate on the "address_line2" field. It's identical to AddressLine2EQ.
func AddressLine2(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAddressLine2, v))
}

// City applies equality check predicate on the "city" field. It's identical to CityEQ.
func City(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCity, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRegion, v))
}

// PostalCode applies equality check predicate on the "postal_code" field. It's identical to PostalCodeEQ.
func PostalCode(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldPostalCode, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCountry, v))
}

// Latitude applies equality check predicate on the "latitude" field. It's identical to LatitudeEQ.
func Latitude(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLatitude, v))
}

// Longitude applies equality check predicate on the "longitude" field. It's identical to LongitudeEQ.
func Longitude(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLongitude, v))
}

// CheckinTime applies equality check predicate on the "checkin_time" field. It's identical to CheckinTimeEQ.
func CheckinTime(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCheckinTime, v))
}

// CheckoutTime applies equality check predicate on the "checkout_time" field. It's identical to CheckoutTimeEQ.
func CheckoutTime(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCheckoutTime, v))
}

// MinNights applies equality check predicate on the "min_nights" field. It's identical to MinNightsEQ.
func MinNights(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMinNights, v))
}

// MaxNights applies equality check predicate on the "max_nights" field. It's identical to MaxNightsEQ.
func MaxNights(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMaxNights, v))
}

// PetsAllowed applies equality check predicate on the "pets_allowed" field. It's identical to PetsAllowedEQ.
func PetsAllowed(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldPetsAllowed, v))
}

// SmokingAllowed applies equality check predicate on the "smoking_allowed" field. It's identical to SmokingAllowedEQ.
func SmokingAllowed(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldSmokingAllowed, v))
}

// HouseRules applies equality check predicate on the "house_rules" field. It's identical to HouseRulesEQ.
func HouseRules(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldHouseRules, v))
}

// SubmittedAt applies equality check predicate on the "submitted_at" field. It's identical to SubmittedAtEQ.
func SubmittedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldSubmittedAt, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewNotes applies equality check predicate on the "review_notes" field. It's identical to ReviewNotesEQ.
func ReviewNotes(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldOwnerID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldTitle, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldType, vs...))
}

// DescriptionShortEQ applies the EQ predicate on the "description_short" field.
func DescriptionShortEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldDescriptionShort, v))
}

// DescriptionShortNEQ applies the NEQ predicate on the "description_short" field.
func DescriptionShortNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldDescriptionShort, v))
}

// DescriptionShortIn applies the In predicate on the "description_short" field.
func DescriptionShortIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldDescriptionShort, vs...))
}

// DescriptionShortNotIn applies the NotIn predicate on the "description_short" field.
func DescriptionShortNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldDescriptionShort, vs...))
}

// DescriptionShortGT applies the GT predicate on the "description_short" field.
func DescriptionShortGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldDescriptionShort, v))
}

// DescriptionShortGTE applies the GTE predicate on the "description_short" field.
func DescriptionShortGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldDescriptionShort, v))
}

// DescriptionShortLT applies the LT predicate on the "description_short" field.
func DescriptionShortLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldDescriptionShort, v))
}

// DescriptionShortLTE applies the LTE predicate on the "description_short" field.
func DescriptionShortLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldDescriptionShort, v))
}

// DescriptionShortContains applies the Contains predicate on the "description_short" field.
func DescriptionShortContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldDescriptionShort, v))
}

// DescriptionShortHasPrefix applies the HasPrefix predicate on the "description_short" field.
func DescriptionShortHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldDescriptionShort, v))
}

// DescriptionShortHasSuffix applies the HasSuffix predicate on the "description_short" field.
func DescriptionShortHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldDescriptionShort, v))
}

// DescriptionShortIsNil applies the IsNil predicate on the "description_short" field.
func DescriptionShortIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldDescriptionShort))
}

// DescriptionShortNotNil applies the NotNil predicate on the "description_short" field.
func DescriptionShortNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldDescriptionShort))
}

// DescriptionShortEqualFold applies the EqualFold predicate on the "description_short" field.
func DescriptionShortEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldDescriptionShort, v))
}

// DescriptionShortContainsFold applies the ContainsFold predicate on the "description_short" field.
func DescriptionShortContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldDescriptionShort, v))
}

// DescriptionLongEQ applies the EQ predicate on the "description_long" field.
func DescriptionLongEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldDescriptionLong, v))
}

// DescriptionLongNEQ applies the NEQ predicate on the "description_long" field.
func DescriptionLongNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldDescriptionLong, v))
}

// DescriptionLongIn applies the In predicate on the "description_long" field.
func DescriptionLongIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldDescriptionLong, vs...))
}

// DescriptionLongNotIn applies the NotIn predicate on the "description_long" field.
func DescriptionLongNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldDescriptionLong, vs...))
}

// DescriptionLongGT applies the GT predicate on the "description_long" field.
func DescriptionLongGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldDescriptionLong, v))
}

// DescriptionLongGTE applies the GTE predicate on the "description_long" field.
func DescriptionLongGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldDescriptionLong, v))
}

// DescriptionLongLT applies the LT predicate on the "description_long" field.
func DescriptionLongLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldDescriptionLong, v))
}

// DescriptionLongLTE applies the LTE predicate on the "description_long" field.
func DescriptionLongLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldDescriptionLong, v))
}

// DescriptionLongContains applies the Contains predicate on the "description_long" field.
func DescriptionLongContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldDescriptionLong, v))
}

// DescriptionLongHasPrefix applies the HasPrefix predicate on the "description_long" field.
func DescriptionLongHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldDescriptionLong, v))
}

// DescriptionLongHasSuffix applies the HasSuffix predicate on the "description_long" field.
func DescriptionLongHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldDescriptionLong, v))
}

// DescriptionLongIsNil applies the IsNil predicate on the "description_long" field.
func DescriptionLongIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldDescriptionLong))
}

// DescriptionLongNotNil applies the NotNil predicate on the "description_long" field.
func DescriptionLongNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldDescriptionLong))
}

// DescriptionLongEqualFold applies the EqualFold predicate on the "description_long" field.
func DescriptionLongEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldDescriptionLong, v))
}

// DescriptionLongContainsFold applies the ContainsFold predicate on the "description_long" field.
func DescriptionLongContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldDescriptionLong, v))
}

// MaxGuestsEQ applies the EQ predicate on the "max_guests" field.
func MaxGuestsEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMaxGuests, v))
}

// MaxGuestsNEQ applies the NEQ predicate on the "max_guests" field.
func MaxGuestsNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldMaxGuests, v))
}

// MaxGuestsIn applies the In predicate on the "max_guests" field.
func MaxGuestsIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldMaxGuests, vs...))
}

// MaxGuestsNotIn applies the NotIn predicate on the "max_guests" field.
func MaxGuestsNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldMaxGuests, vs...))
}

// MaxGuestsGT applies the GT predicate on the "max_guests" field.
func MaxGuestsGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldMaxGuests, v))
}

// MaxGuestsGTE applies the GTE predicate on the "max_guests" field.
func MaxGuestsGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldMaxGuests, v))
}

// MaxGuestsLT applies the LT predicate on the "max_guests" field.
func MaxGuestsLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldMaxGuests, v))
}

// MaxGuestsLTE applies the LTE predicate on the "max_guests" field.
func MaxGuestsLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldMaxGuests, v))
}

// MaxGuestsIsNil applies the IsNil predicate on the "max_guests" field.
func MaxGuestsIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldMaxGuests))
}

// MaxGuestsNotNil applies the NotNil predicate on the "max_guests" field.
func MaxGuestsNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldMaxGuests))
}

// BathroomsTotalEQ applies the EQ predicate on the "bathrooms_total" field.
func BathroomsTotalEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldBathroomsTotal, v))
}

// BathroomsTotalNEQ applies the NEQ predicate on the "bathrooms_total" field.
func BathroomsTotalNEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldBathroomsTotal, v))
}

// BathroomsTotalIn applies the In predicate on the "bathrooms_total" field.
func BathroomsTotalIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldBathroomsTotal, vs...))
}

// BathroomsTotalNotIn applies the NotIn predicate on the "bathrooms_total" field.
func BathroomsTotalNotIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldBathroomsTotal, vs...))
}

// BathroomsTotalGT applies the GT predicate on the "bathrooms_total" field.
func BathroomsTotalGT(v float64) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldBathroomsTotal, v))
}

// BathroomsTotalGTE applies the GTE predicate on the "bathrooms_total" field.
func BathroomsTotalGTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldBathroomsTotal, v))
}

// BathroomsTotalLT applies the LT predicate on the "bathrooms_total" field.
func BathroomsTotalLT(v float64) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldBathroomsTotal, v))
}

// BathroomsTotalLTE applies the LTE predicate on the "bathrooms_total" field.
func BathroomsTotalLTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldBathroomsTotal, v))
}

// BathroomsTotalIsNil applies the IsNil predicate on the "bathrooms_total" field.
func BathroomsTotalIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldBathroomsTotal))
}

// BathroomsTotalNotNil applies the NotNil predicate on the "bathrooms_total" field.
func BathroomsTotalNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldBathroomsTotal))
}

// AddressLine1EQ applies the EQ predicate on the "address_line1" field.
func AddressLine1EQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAddressLine1, v))
}

// AddressLine1NEQ applies the NEQ predicate on the "address_line1" field.
func AddressLine1NEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldAddressLine1, v))
}

// AddressLine1In applies the In predicate on the "address_line1" field.
func AddressLine1In(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldAddressLine1, vs...))
}

// AddressLine1NotIn applies the NotIn predicate on the "address_line1" field.
func AddressLine1NotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldAddressLine1, vs...))
}

// AddressLine1GT applies the GT predicate on the "address_line1" field.
func AddressLine1GT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldAddressLine1, v))
}

// AddressLine1GTE applies the GTE predicate on the "address_line1" field.
func AddressLine1GTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldAddressLine1, v))
}

// AddressLine1LT applies the LT predicate on the "address_line1" field.
func AddressLine1LT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldAddressLine1, v))
}

// AddressLine1LTE applies the LTE predicate on the "address_line1" field.
func AddressLine1LTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldAddressLine1, v))
}

// AddressLine1Contains applies the Contains predicate on the "address_line1" field.
func AddressLine1Contains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldAddressLine1, v))
}

// AddressLine1HasPrefix applies the HasPrefix predicate on the "address_line1" field.
func AddressLine1HasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldAddressLine1, v))
}

// AddressLine1HasSuffix applies the HasSuffix predicate on the "address_line1" field.
func AddressLine1HasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldAddressLine1, v))
}

// AddressLine1EqualFold applies the EqualFold predicate on the "address_line1" field.
func AddressLine1EqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldAddressLine1, v))
}

// AddressLine1ContainsFold applies the ContainsFold predicate on the "address_line1" field.
func AddressLine1ContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldAddressLine1, v))
}

// AddressLine2EQ applies the EQ predicate on the "address_line2" field.
func AddressLine2EQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldAddressLine2, v))
}

// AddressLine2NEQ applies the NEQ predicate on the "address_line2" field.
func AddressLine2NEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldAddressLine2, v))
}

// AddressLine2In applies the In predicate on the "address_line2" field.
func AddressLine2In(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldAddressLine2, vs...))
}

// AddressLine2NotIn applies the NotIn predicate on the "address_line2" field.
func AddressLine2NotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldAddressLine2, vs...))
}

// AddressLine2GT applies the GT predicate on the "address_line2" field.
func AddressLine2GT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldAddressLine2, v))
}

// AddressLine2GTE applies the GTE predicate on the "address_line2" field.
func AddressLine2GTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldAddressLine2, v))
}

// AddressLine2LT applies the LT predicate on the "address_line2" field.
func AddressLine2LT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldAddressLine2, v))
}

// AddressLine2LTE applies the LTE predicate on the "address_line2" field.
func AddressLine2LTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldAddressLine2, v))
}

// AddressLine2Contains applies the Contains predicate on the "address_line2" field.
func AddressLine2Contains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldAddressLine2, v))
}

// AddressLine2HasPrefix applies the HasPrefix predicate on the "address_line2" field.
func AddressLine2HasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldAddressLine2, v))
}

// AddressLine2HasSuffix applies the HasSuffix predicate on the "address_line2" field.
func AddressLine2HasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldAddressLine2, v))
}

// AddressLine2IsNil applies the IsNil predicate on the "address_line2" field.
func AddressLine2IsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldAddressLine2))
}

// AddressLine2NotNil applies the NotNil predicate on the "address_line2" field.
func AddressLine2NotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldAddressLine2))
}

// AddressLine2EqualFold applies the EqualFold predicate on the "address_line2" field.
func AddressLine2EqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldAddressLine2, v))
}

// AddressLine2ContainsFold applies the ContainsFold predicate on the "address_line2" field.
func AddressLine2ContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldAddressLine2, v))
}

// CityEQ applies the EQ predicate on the "city" field.
func CityEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCity, v))
}

// CityNEQ applies the NEQ predicate on the "city" field.
func CityNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCity, v))
}

// CityIn applies the In predicate on the "city" field.
func CityIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCity, vs...))
}

// CityNotIn applies the NotIn predicate on the "city" field.
func CityNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCity, vs...))
}

// CityGT applies the GT predicate on the "city" field.
func CityGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCity, v))
}

// CityGTE applies the GTE predicate on the "city" field.
func CityGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCity, v))
}

// CityLT applies the LT predicate on the "city" field.
func CityLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCity, v))
}

// CityLTE applies the LTE predicate on the "city" field.
func CityLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCity, v))
}

// CityContains applies the Contains predicate on the "city" field.
func CityContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldCity, v))
}

// CityHasPrefix applies the HasPrefix predicate on the "city" field.
func CityHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldCity, v))
}

// CityHasSuffix applies the HasSuffix predicate on the "city" field.
func CityHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldCity, v))
}

// CityEqualFold applies the EqualFold predicate on the "city" field.
func CityEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldCity, v))
}

// CityContainsFold applies the ContainsFold predicate on the "city" field.
func CityContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldCity, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldRegion, v))
}

// PostalCodeEQ applies the EQ predicate on the "postal_code" field.
func PostalCodeEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldPostalCode, v))
}

// PostalCodeNEQ applies the NEQ predicate on the "postal_code" field.
func PostalCodeNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldPostalCode, v))
}

// PostalCodeIn applies the In predicate on the "postal_code" field.
func PostalCodeIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldPostalCode, vs...))
}

// PostalCodeNotIn applies the NotIn predicate on the "postal_code" field.
func PostalCodeNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldPostalCode, vs...))
}

// PostalCodeGT applies the GT predicate on the "postal_code" field.
func PostalCodeGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldPostalCode, v))
}

// PostalCodeGTE applies the GTE predicate on the "postal_code" field.
func PostalCodeGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldPostalCode, v))
}

// PostalCodeLT applies the LT predicate on the "postal_code" field.
func PostalCodeLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldPostalCode, v))
}

// PostalCodeLTE applies the LTE predicate on the "postal_code" field.
func PostalCodeLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldPostalCode, v))
}

// PostalCodeContains applies the Contains predicate on the "postal_code" field.
func PostalCodeContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldPostalCode, v))
}

// PostalCodeHasPrefix applies the HasPrefix predicate on the "postal_code" field.
func PostalCodeHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldPostalCode, v))
}

// PostalCodeHasSuffix applies the HasSuffix predicate on the "postal_code" field.
func PostalCodeHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldPostalCode, v))
}

// PostalCodeEqualFold applies the EqualFold predicate on the "postal_code" field.
func PostalCodeEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldPostalCode, v))
}

// PostalCodeContainsFold applies the ContainsFold predicate on the "postal_code" field.
func PostalCodeContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldPostalCode, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldCountry, v))
}

// LatitudeEQ applies the EQ predicate on the "latitude" field.
func LatitudeEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLatitude, v))
}

// LatitudeNEQ applies the NEQ predicate on the "latitude" field.
func LatitudeNEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldLatitude, v))
}

// LatitudeIn applies the In predicate on the "latitude" field.
func LatitudeIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldLatitude, vs...))
}

// LatitudeNotIn applies the NotIn predicate on the "latitude" field.
func LatitudeNotIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldLatitude, vs...))
}

// LatitudeGT applies the GT predicate on the "latitude" field.
func LatitudeGT(v float64) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldLatitude, v))
}

// LatitudeGTE applies the GTE predicate on the "latitude" field.
func LatitudeGTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldLatitude, v))
}

// LatitudeLT applies the LT predicate on the "latitude" field.
func LatitudeLT(v float64) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldLatitude, v))
}

// LatitudeLTE applies the LTE predicate on the "latitude" field.
func LatitudeLTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldLatitude, v))
}

// LatitudeIsNil applies the IsNil predicate on the "latitude" field.
func LatitudeIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldLatitude))
}

// LatitudeNotNil applies the NotNil predicate on the "latitude" field.
func LatitudeNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldLatitude))
}

// LongitudeEQ applies the EQ predicate on the "longitude" field.
func LongitudeEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldLongitude, v))
}

// LongitudeNEQ applies the NEQ predicate on the "longitude" field.
func LongitudeNEQ(v float64) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldLongitude, v))
}

// LongitudeIn applies the In predicate on the "longitude" field.
func LongitudeIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldLongitude, vs...))
}

// LongitudeNotIn applies the NotIn predicate on the "longitude" field.
func LongitudeNotIn(vs ...float64) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldLongitude, vs...))
}

// LongitudeGT applies the GT predicate on the "longitude" field.
func LongitudeGT(v float64) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldLongitude, v))
}

// LongitudeGTE applies the GTE predicate on the "longitude" field.
func LongitudeGTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldLongitude, v))
}

// LongitudeLT applies the LT predicate on the "longitude" field.
func LongitudeLT(v float64) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldLongitude, v))
}

// LongitudeLTE applies the LTE predicate on the "longitude" field.
func LongitudeLTE(v float64) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldLongitude, v))
}

// LongitudeIsNil applies the IsNil predicate on the "longitude" field.
func LongitudeIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldLongitude))
}

// LongitudeNotNil applies the NotNil predicate on the "longitude" field.
func LongitudeNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldLongitude))
}

// CheckinTimeEQ applies the EQ predicate on the "checkin_time" field.
func CheckinTimeEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCheckinTime, v))
}

// CheckinTimeNEQ applies the NEQ predicate on the "checkin_time" field.
func CheckinTimeNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCheckinTime, v))
}

// CheckinTimeIn applies the In predicate on the "checkin_time" field.
func CheckinTimeIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCheckinTime, vs...))
}

// CheckinTimeNotIn applies the NotIn predicate on the "checkin_time" field.
func CheckinTimeNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCheckinTime, vs...))
}

// CheckinTimeGT applies the GT predicate on the "checkin_time" field.
func CheckinTimeGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCheckinTime, v))
}

// CheckinTimeGTE applies the GTE predicate on the "checkin_time" field.
func CheckinTimeGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCheckinTime, v))
}

// CheckinTimeLT applies the LT predicate on the "checkin_time" field.
func CheckinTimeLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCheckinTime, v))
}

// CheckinTimeLTE applies the LTE predicate on the "checkin_time" field.
func CheckinTimeLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCheckinTime, v))
}

// CheckinTimeIsNil applies the IsNil predicate on the "checkin_time" field.
func CheckinTimeIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldCheckinTime))
}

// CheckinTimeNotNil applies the NotNil predicate on the "checkin_time" field.
func CheckinTimeNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldCheckinTime))
}

// CheckoutTimeEQ applies the EQ predicate on the "checkout_time" field.
func CheckoutTimeEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCheckoutTime, v))
}

// CheckoutTimeNEQ applies the NEQ predicate on the "checkout_time" field.
func CheckoutTimeNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCheckoutTime, v))
}

// CheckoutTimeIn applies the In predicate on the "checkout_time" field.
func CheckoutTimeIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCheckoutTime, vs...))
}

// CheckoutTimeNotIn applies the NotIn predicate on the "checkout_time" field.
func CheckoutTimeNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCheckoutTime, vs...))
}

// CheckoutTimeGT applies the GT predicate on the "checkout_time" field.
func CheckoutTimeGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCheckoutTime, v))
}

// CheckoutTimeGTE applies the GTE predicate on the "checkout_time" field.
func CheckoutTimeGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCheckoutTime, v))
}

// CheckoutTimeLT applies the LT predicate on the "checkout_time" field.
func CheckoutTimeLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCheckoutTime, v))
}

// CheckoutTimeLTE applies the LTE predicate on the "checkout_time" field.
func CheckoutTimeLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCheckoutTime, v))
}

// CheckoutTimeIsNil applies the IsNil predicate on the "checkout_time" field.
func CheckoutTimeIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldCheckoutTime))
}

// CheckoutTimeNotNil applies the NotNil predicate on the "checkout_time" field.
func CheckoutTimeNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldCheckoutTime))
}

// MinNightsEQ applies the EQ predicate on the "min_nights" field.
func MinNightsEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMinNights, v))
}

// MinNightsNEQ applies the NEQ predicate on the "min_nights" field.
func MinNightsNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldMinNights, v))
}

// MinNightsIn applies the In predicate on the "min_nights" field.
func MinNightsIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldMinNights, vs...))
}

// MinNightsNotIn applies the NotIn predicate on the "min_nights" field.
func MinNightsNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldMinNights, vs...))
}

// MinNightsGT applies the GT predicate on the "min_nights" field.
func MinNightsGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldMinNights, v))
}

// MinNightsGTE applies the GTE predicate on the "min_nights" field.
func MinNightsGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldMinNights, v))
}

// MinNightsLT applies the LT predicate on the "min_nights" field.
func MinNightsLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldMinNights, v))
}

// MinNightsLTE applies the LTE predicate on the "min_nights" field.
func MinNightsLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldMinNights, v))
}

// MinNightsIsNil applies the IsNil predicate on the "min_nights" field.
func MinNightsIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldMinNights))
}

// MinNightsNotNil applies the NotNil predicate on the "min_nights" field.
func MinNightsNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldMinNights))
}

// MaxNightsEQ applies the EQ predicate on the "max_nights" field.
func MaxNightsEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldMaxNights, v))
}

// MaxNightsNEQ applies the NEQ predicate on the "max_nights" field.
func MaxNightsNEQ(v int) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldMaxNights, v))
}

// MaxNightsIn applies the In predicate on the "max_nights" field.
func MaxNightsIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldMaxNights, vs...))
}

// MaxNightsNotIn applies the NotIn predicate on the "max_nights" field.
func MaxNightsNotIn(vs ...int) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldMaxNights, vs...))
}

// MaxNightsGT applies the GT predicate on the "max_nights" field.
func MaxNightsGT(v int) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldMaxNights, v))
}

// MaxNightsGTE applies the GTE predicate on the "max_nights" field.
func MaxNightsGTE(v int) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldMaxNights, v))
}

// MaxNightsLT applies the LT predicate on the "max_nights" field.
func MaxNightsLT(v int) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldMaxNights, v))
}

// MaxNightsLTE applies the LTE predicate on the "max_nights" field.
func MaxNightsLTE(v int) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldMaxNights, v))
}

// MaxNightsIsNil applies the IsNil predicate on the "max_nights" field.
func MaxNightsIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldMaxNights))
}

// MaxNightsNotNil applies the NotNil predicate on the "max_nights" field.
func MaxNightsNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldMaxNights))
}

// PetsAllowedEQ applies the EQ predicate on the "pets_allowed" field.
func PetsAllowedEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldPetsAllowed, v))
}

// PetsAllowedNEQ applies the NEQ predicate on the "pets_allowed" field.
func PetsAllowedNEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldPetsAllowed, v))
}

// SmokingAllowedEQ applies the EQ predicate on the "smoking_allowed" field.
func SmokingAllowedEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldSmokingAllowed, v))
}

// SmokingAllowedNEQ applies the NEQ predicate on the "smoking_allowed" field.
func SmokingAllowedNEQ(v bool) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldSmokingAllowed, v))
}

// HouseRulesEQ applies the EQ predicate on the "house_rules" field.
func HouseRulesEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldHouseRules, v))
}

// HouseRulesNEQ applies the NEQ predicate on the "house_rules" field.
func HouseRulesNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldHouseRules, v))
}

// HouseRulesIn applies the In predicate on the "house_rules" field.
func HouseRulesIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldHouseRules, vs...))
}

// HouseRulesNotIn applies the NotIn predicate on the "house_rules" field.
func HouseRulesNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldHouseRules, vs...))
}

// HouseRulesGT applies the GT predicate on the "house_rules" field.
func HouseRulesGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldHouseRules, v))
}

// HouseRulesGTE applies the GTE predicate on the "house_rules" field.
func HouseRulesGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldHouseRules, v))
}

// HouseRulesLT applies the LT predicate on the "house_rules" field.
func HouseRulesLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldHouseRules, v))
}

// HouseRulesLTE applies the LTE predicate on the "house_rules" field.
func HouseRulesLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldHouseRules, v))
}

// HouseRulesContains applies the Contains predicate on the "house_rules" field.
func HouseRulesContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldHouseRules, v))
}

// HouseRulesHasPrefix applies the HasPrefix predicate on the "house_rules" field.
func HouseRulesHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldHouseRules, v))
}

// HouseRulesHasSuffix applies the HasSuffix predicate on the "house_rules" field.
func HouseRulesHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldHouseRules, v))
}

// HouseRulesIsNil applies the IsNil predicate on the "house_rules" field.
func HouseRulesIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldHouseRules))
}

// HouseRulesNotNil applies the NotNil predicate on the "house_rules" field.
func HouseRulesNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldHouseRules))
}

// HouseRulesEqualFold applies the EqualFold predicate on the "house_rules" field.
func HouseRulesEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldHouseRules, v))
}

// HouseRulesContainsFold applies the ContainsFold predicate on the "house_rules" field.
func HouseRulesContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldHouseRules, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldStatus, vs...))
}

// SubmittedAtEQ applies the EQ predicate on the "submitted_at" field.
func SubmittedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldSubmittedAt, v))
}

// SubmittedAtNEQ applies the NEQ predicate on the "submitted_at" field.
func SubmittedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldSubmittedAt, v))
}

// SubmittedAtIn applies the In predicate on the "submitted_at" field.
func SubmittedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldSubmittedAt, vs...))
}

// SubmittedAtNotIn applies the NotIn predicate on the "submitted_at" field.
func SubmittedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldSubmittedAt, vs...))
}

// SubmittedAtGT applies the GT predicate on the "submitted_at" field.
func SubmittedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldSubmittedAt, v))
}

// SubmittedAtGTE applies the GTE predicate on the "submitted_at" field.
func SubmittedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldSubmittedAt, v))
}

// SubmittedAtLT applies the LT predicate on the "submitted_at" field.
func SubmittedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldSubmittedAt, v))
}

// SubmittedAtLTE applies the LTE predicate on the "submitted_at" field.
func SubmittedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldSubmittedAt, v))
}

// SubmittedAtIsNil applies the IsNil predicate on the "submitted_at" field.
func SubmittedAtIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldSubmittedAt))
}

// SubmittedAtNotNil applies the NotNil predicate on the "submitted_at" field.
func SubmittedAtNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldSubmittedAt))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...uuid.UUID) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldReviewedAt))
}

// ReviewNotesEQ applies the EQ predicate on the "review_notes" field.
func ReviewNotesEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldReviewNotes, v))
}

// ReviewNotesNEQ applies the NEQ predicate on the "review_notes" field.
func ReviewNotesNEQ(v string) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldReviewNotes, v))
}

// ReviewNotesIn applies the In predicate on the "review_notes" field.
func ReviewNotesIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldReviewNotes, vs...))
}

// ReviewNotesNotIn applies the NotIn predicate on the "review_notes" field.
func ReviewNotesNotIn(vs ...string) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldReviewNotes, vs...))
}

// ReviewNotesGT applies the GT predicate on the "review_notes" field.
func ReviewNotesGT(v string) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldReviewNotes, v))
}

// ReviewNotesGTE applies the GTE predicate on the "review_notes" field.
func ReviewNotesGTE(v string) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldReviewNotes, v))
}

// ReviewNotesLT applies the LT predicate on the "review_notes" field.
func ReviewNotesLT(v string) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldReviewNotes, v))
}

// ReviewNotesLTE applies the LTE predicate on the "review_notes" field.
func ReviewNotesLTE(v string) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldReviewNotes, v))
}

// ReviewNotesContains applies the Contains predicate on the "review_notes" field.
func ReviewNotesContains(v string) predicate.Property {
	return predicate.Property(sql.FieldContains(FieldReviewNotes, v))
}

// ReviewNotesHasPrefix applies the HasPrefix predicate on the "review_notes" field.
func ReviewNotesHasPrefix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasPrefix(FieldReviewNotes, v))
}

// ReviewNotesHasSuffix applies the HasSuffix predicate on the "review_notes" field.
func ReviewNotesHasSuffix(v string) predicate.Property {
	return predicate.Property(sql.FieldHasSuffix(FieldReviewNotes, v))
}

// ReviewNotesIsNil applies the IsNil predicate on the "review_notes" field.
func ReviewNotesIsNil() predicate.Property {
	return predicate.Property(sql.FieldIsNull(FieldReviewNotes))
}

// ReviewNotesNotNil applies the NotNil predicate on the "review_notes" field.
func ReviewNotesNotNil() predicate.Property {
	return predicate.Property(sql.FieldNotNull(FieldReviewNotes))
}

// ReviewNotesEqualFold applies the EqualFold predicate on the "review_notes" field.
func ReviewNotesEqualFold(v string) predicate.Property {
	return predicate.Property(sql.FieldEqualFold(FieldReviewNotes, v))
}

// ReviewNotesContainsFold applies the ContainsFold predicate on the "review_notes" field.
func ReviewNotesContainsFold(v string) predicate.Property {
	return predicate.Property(sql.FieldContainsFold(FieldReviewNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Property {
	return predicate.Property(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Property {
	return predicate.Property(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviewer applies the HasEdge predicate on the "reviewer" edge.
func HasReviewer() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ReviewerTable, ReviewerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewerWith applies the HasEdge predicate on the "reviewer" edge with a given conditions (other predicates).
func HasReviewerWith(preds ...predicate.User) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newReviewerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRooms applies the HasEdge predicate on the "rooms" edge.
func HasRooms() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RoomsTable, RoomsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomsWith applies the HasEdge predicate on the "rooms" edge with a given conditions (other predicates).
func HasRoomsWith(preds ...predicate.Room) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newRoomsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAmenities applies the HasEdge predicate on the "amenities" edge.
func HasAmenities() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, AmenitiesTable, AmenitiesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAmenitiesWith applies the HasEdge predicate on the "amenities" edge with a given conditions (other predicates).
func HasAmenitiesWith(preds ...predicate.Amenity) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newAmenitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPropertyAmenities applies the HasEdge predicate on the "property_amenities" edge.
func HasPropertyAmenities() predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, PropertyAmenitiesTable, PropertyAmenitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyAmenitiesWith applies the HasEdge predicate on the "property_amenities" edge with a given conditions (other predicates).
func HasPropertyAmenitiesWith(preds ...predicate.PropertyAmenity) predicate.Property {
	return predicate.Property(func(s *sql.Selector) {
		step := newPropertyAmenitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Property) predicate.Property {
	return predicate.Property(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Property) predicate.Property {
	return predicate.Property(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Property) predicate.Property {
	return predicate.Property(sql.NotPredicates(p))
}
