// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AmenitiesColumns holds the columns for the "amenities" table.
	AmenitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "category", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AmenitiesTable holds the schema information for the "amenities" table.
	AmenitiesTable = &schema.Table{
		Name:       "amenities",
		Columns:    AmenitiesColumns,
		PrimaryKey: []*schema.Column{AmenitiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "amenity_code",
				Unique:  true,
				Columns: []*schema.Column{AmenitiesColumns[1]},
			},
		},
	}
	// PropertiesColumns holds the columns for the "properties" table.
	PropertiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"house", "apartment", "condo", "cabin", "villa", "townhouse", "other"}, Default: "other"},
		{Name: "description_short", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "description_long", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "max_guests", Type: field.TypeInt, Nullable: true},
		{Name: "bathrooms_total", Type: field.TypeFloat64, Nullable: true},
		{Name: "address_line1", Type: field.TypeString},
		{Name: "address_line2", Type: field.TypeString, Nullable: true},
		{Name: "city", Type: field.TypeString},
		{Name: "region", Type: field.TypeString},
		{Name: "postal_code", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "longitude", Type: field.TypeFloat64, Nullable: true},
		{Name: "checkin_time", Type: field.TypeTime, Nullable: true},
		{Name: "checkout_time", Type: field.TypeTime, Nullable: true},
		{Name: "min_nights", Type: field.TypeInt, Nullable: true},
		{Name: "max_nights", Type: field.TypeInt, Nullable: true},
		{Name: "pets_allowed", Type: field.TypeBool, Default: false},
		{Name: "smoking_allowed", Type: field.TypeBool, Default: false},
		{Name: "house_rules", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "submitted", "under_review", "approved", "rejected"}, Default: "draft"},
		{Name: "submitted_at", Type: field.TypeTime, Nullable: true},
		{Name: "reviewed_at", Type: field.TypeTime, Nullable: true},
		{Name: "review_notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "reviewed_by", Type: field.TypeUUID, Unique: true, Nullable: true},
	}
	// PropertiesTable holds the schema information for the "properties" table.
	PropertiesTable = &schema.Table{
		Name:       "properties",
		Columns:    PropertiesColumns,
		PrimaryKey: []*schema.Column{PropertiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "properties_users_properties",
				Columns:    []*schema.Column{PropertiesColumns[28]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "properties_users_reviewed_properties",
				Columns:    []*schema.Column{PropertiesColumns[29]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "property_owner_id_status",
				Unique:  false,
				Columns: []*schema.Column{PropertiesColumns[28], PropertiesColumns[22]},
			},
		},
	}
	// PropertyAmenitiesColumns holds the columns for the "property_amenities" table.
	PropertyAmenitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "property_id", Type: field.TypeUUID},
		{Name: "amenity_id", Type: field.TypeUUID},
	}
	// PropertyAmenitiesTable holds the schema information for the "property_amenities" table.
	PropertyAmenitiesTable = &schema.Table{
		Name:       "property_amenities",
		Columns:    PropertyAmenitiesColumns,
		PrimaryKey: []*schema.Column{PropertyAmenitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "property_amenities_properties_property",
				Columns:    []*schema.Column{PropertyAmenitiesColumns[2]},
				RefColumns: []*schema.Column{PropertiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "property_amenities_amenities_amenity",
				Columns:    []*schema.Column{PropertyAmenitiesColumns[3]},
				RefColumns: []*schema.Column{AmenitiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "propertyamenity_property_id",
				Unique:  false,
				Columns: []*schema.Column{PropertyAmenitiesColumns[2]},
			},
			{
				Name:    "propertyamenity_amenity_id",
				Unique:  false,
				Columns: []*schema.Column{PropertyAmenitiesColumns[3]},
			},
			{
				Name:    "propertyamenity_property_id_amenity_id",
				Unique:  true,
				Columns: []*schema.Column{PropertyAmenitiesColumns[2], PropertyAmenitiesColumns[3]},
			},
		},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "floor_label", Type: field.TypeString, Nullable: true},
		{Name: "area_sq_ft", Type: field.TypeInt, Nullable: true},
		{Name: "bed_mix", Type: field.TypeJSON},
		{Name: "ensuite_bath", Type: field.TypeBool, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "property_id", Type: field.TypeUUID},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:       "rooms",
		Columns:    RoomsColumns,
		PrimaryKey: []*schema.Column{RoomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rooms_properties_rooms",
				Columns:    []*schema.Column{RoomsColumns[9]},
				RefColumns: []*schema.Column{PropertiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "agent"}},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AmenitiesTable,
		PropertiesTable,
		PropertyAmenitiesTable,
		RoomsTable,
		UsersTable,
	}
)

func init() {
	PropertiesTable.ForeignKeys[0].RefTable = UsersTable
	PropertiesTable.ForeignKeys[1].RefTable = UsersTable
	PropertyAmenitiesTable.ForeignKeys[0].RefTable = PropertiesTable
	PropertyAmenitiesTable.ForeignKeys[1].RefTable = AmenitiesTable
	RoomsTable.ForeignKeys[0].RefTable = PropertiesTable
}
