// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Amenity is the predicate function for amenity builders.
type Amenity func(*sql.Selector)

// Property is the predicate function for property builders.
type Property func(*sql.Selector)

// PropertyAmenity is the predicate function for propertyamenity builders.
type PropertyAmenity func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
