// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Node interface {
	IsNode()
	GetID() string
}

// Amenity dictionary row.
type Amenity struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Name      string `json:"name"`
	Category  string `json:"category"`
	CreatedAt string `json:"createdAt"`
}

func (Amenity) IsNode()            {}
func (this Amenity) GetID() string { return this.ID }

type AmenityAttachInput struct {
	Code    string  `json:"code"`
	Details *string `json:"details,omitempty"`
}

type AmenityFilter struct {
	CodeIn     []string `json:"codeIn,omitempty"`
	CategoryIn []string `json:"categoryIn,omitempty"`
	Q          *string  `json:"q,omitempty"`
}

type CountByKey struct {
	Key   string `json:"key"`
	Count int    `json:"count"`
}

type CreatePropertyInput struct {
	Title            string        `json:"title"`
	Type             *PropertyType `json:"type,omitempty"`
	DescriptionShort *string       `json:"descriptionShort,omitempty"`
	DescriptionLong  *string       `json:"descriptionLong,omitempty"`
	MaxGuests        *int          `json:"maxGuests,omitempty"`
	BathroomsTotal   *float64      `json:"bathroomsTotal,omitempty"`
	AddressLine1     string        `json:"addressLine1"`
	AddressLine2     *string       `json:"addressLine2,omitempty"`
	City             string        `json:"city"`
	Region           string        `json:"region"`
	PostalCode       string        `json:"postalCode"`
	Country          string        `json:"country"`
	Latitude         *float64      `json:"latitude,omitempty"`
	Longitude        *float64      `json:"longitude,omitempty"`
	CheckinTime      *time.Time    `json:"checkinTime,omitempty"`
	CheckoutTime     *time.Time    `json:"checkoutTime,omitempty"`
	MinNights        *int          `json:"minNights,omitempty"`
	MaxNights        *int          `json:"maxNights,omitempty"`
	PetsAllowed      *bool         `json:"petsAllowed,omitempty"`
	SmokingAllowed   *bool         `json:"smokingAllowed,omitempty"`
	HouseRules       *string       `json:"houseRules,omitempty"`
}

type Mutation struct {
}

// A vacation rental listing submitted to Evolve.
type Property struct {
	ID               string             `json:"id"`
	Owner            *User              `json:"owner"`
	Title            string             `json:"title"`
	Type             PropertyType       `json:"type"`
	DescriptionShort *string            `json:"descriptionShort,omitempty"`
	DescriptionLong  *string            `json:"descriptionLong,omitempty"`
	MaxGuests        *int               `json:"maxGuests,omitempty"`
	BathroomsTotal   *float64           `json:"bathroomsTotal,omitempty"`
	AddressLine1     string             `json:"addressLine1"`
	AddressLine2     *string            `json:"addressLine2,omitempty"`
	City             string             `json:"city"`
	Region           string             `json:"region"`
	PostalCode       string             `json:"postalCode"`
	Country          string             `json:"country"`
	Latitude         *float64           `json:"latitude,omitempty"`
	Longitude        *float64           `json:"longitude,omitempty"`
	CheckinTime      *time.Time         `json:"checkinTime,omitempty"`
	CheckoutTime     *time.Time         `json:"checkoutTime,omitempty"`
	MinNights        *int               `json:"minNights,omitempty"`
	MaxNights        *int               `json:"maxNights,omitempty"`
	PetsAllowed      bool               `json:"petsAllowed"`
	SmokingAllowed   bool               `json:"smokingAllowed"`
	HouseRules       *string            `json:"houseRules,omitempty"`
	Status           PropertyStatus     `json:"status"`
	SubmittedAt      *string            `json:"submittedAt,omitempty"`
	ReviewedBy       *User              `json:"reviewedBy,omitempty"`
	ReviewedAt       *string            `json:"reviewedAt,omitempty"`
	ReviewNotes      *string            `json:"reviewNotes,omitempty"`
	Rooms            []*Room            `json:"rooms"`
	Amenities        []*PropertyAmenity `json:"amenities"`
	CreatedAt        string             `json:"createdAt"`
	UpdatedAt        string             `json:"updatedAt"`
}

func (Property) IsNode()            {}
func (this Property) GetID() string { return this.ID }

// Edge: Property ↔ Amenity with optional structured details.
type PropertyAmenity struct {
	ID       string    `json:"id"`
	Property *Property `json:"property"`
	Amenity  *Amenity  `json:"amenity"`
	Details  *string   `json:"details,omitempty"`
}

func (PropertyAmenity) IsNode()            {}
func (this PropertyAmenity) GetID() string { return this.ID }

// Wizard draft payloads (optional).
type PropertyDraft struct {
	ID        string    `json:"id"`
	Owner     *User     `json:"owner"`
	Property  *Property `json:"property,omitempty"`
	Step      string    `json:"step"`
	Payload   string    `json:"payload"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

func (PropertyDraft) IsNode()            {}
func (this PropertyDraft) GetID() string { return this.ID }

type PropertyFilter struct {
	Ids             []string         `json:"ids,omitempty"`
	OwnerID         *string          `json:"ownerId,omitempty"`
	StatusIn        []PropertyStatus `json:"statusIn,omitempty"`
	TypeIn          []PropertyType   `json:"typeIn,omitempty"`
	CityEq          *string          `json:"cityEq,omitempty"`
	RegionEq        *string          `json:"regionEq,omitempty"`
	CountryEq       *string          `json:"countryEq,omitempty"`
	PetsAllowed     *bool            `json:"petsAllowed,omitempty"`
	SmokingAllowed  *bool            `json:"smokingAllowed,omitempty"`
	MinGuestsGte    *int             `json:"minGuestsGte,omitempty"`
	MinBathroomsGte *float64         `json:"minBathroomsGte,omitempty"`
	AmenitiesAllOf  []string         `json:"amenitiesAllOf,omitempty"`
	AmenitiesAnyOf  []string         `json:"amenitiesAnyOf,omitempty"`
	CreatedFrom     *string          `json:"createdFrom,omitempty"`
	CreatedTo       *string          `json:"createdTo,omitempty"`
	SubmittedFrom   *string          `json:"submittedFrom,omitempty"`
	SubmittedTo     *string          `json:"submittedTo,omitempty"`
	LatMin          *float64         `json:"latMin,omitempty"`
	LatMax          *float64         `json:"latMax,omitempty"`
	LonMin          *float64         `json:"lonMin,omitempty"`
	LonMax          *float64         `json:"lonMax,omitempty"`
	FullText        *string          `json:"fullText,omitempty"`
}

type PropertySortInput struct {
	By        PropertySortBy `json:"by"`
	Direction SortDirection  `json:"direction"`
}

type Query struct {
}

type ReviewPropertyInput struct {
	PropertyID string         `json:"propertyId"`
	Decision   ReviewDecision `json:"decision"`
	Notes      *string        `json:"notes,omitempty"`
}

// A physical room inside a property.
type Room struct {
	ID          string     `json:"id"`
	Property    *Property  `json:"property"`
	Name        string     `json:"name"`
	FloorLabel  *string    `json:"floorLabel,omitempty"`
	AreaSqFt    *int       `json:"areaSqFt,omitempty"`
	EnsuiteBath *bool      `json:"ensuiteBath,omitempty"`
	Beds        []*RoomBed `json:"beds"`
	Notes       *string    `json:"notes,omitempty"`
	CreatedAt   string     `json:"createdAt"`
	UpdatedAt   string     `json:"updatedAt"`
}

func (Room) IsNode()            {}
func (this Room) GetID() string { return this.ID }

// A structured bed entry.
type RoomBed struct {
	Type  BedType `json:"type"`
	Count int     `json:"count"`
}

type RoomBedInput struct {
	Type  BedType `json:"type"`
	Count int     `json:"count"`
}

type RoomFilter struct {
	PropertyID   *string   `json:"propertyId,omitempty"`
	NameContains *string   `json:"nameContains,omitempty"`
	EnsuiteBath  *bool     `json:"ensuiteBath,omitempty"`
	BedAnyOf     []BedType `json:"bedAnyOf,omitempty"`
}

type RoomUpsert struct {
	ID          *string         `json:"id,omitempty"`
	Name        string          `json:"name"`
	FloorLabel  *string         `json:"floorLabel,omitempty"`
	AreaSqFt    *int            `json:"areaSqFt,omitempty"`
	EnsuiteBath *bool           `json:"ensuiteBath,omitempty"`
	Beds        []*RoomBedInput `json:"beds"`
	Notes       *string         `json:"notes,omitempty"`
}

type SaveDraftInput struct {
	Step       string  `json:"step"`
	Payload    string  `json:"payload"`
	PropertyID *string `json:"propertyId,omitempty"`
}

type SetAmenitiesInput struct {
	PropertyID string                `json:"propertyId"`
	Amenities  []*AmenityAttachInput `json:"amenities"`
}

type SubmitPropertyInput struct {
	PropertyID string `json:"propertyId"`
}

type UpsertRoomsInput struct {
	PropertyID string        `json:"propertyId"`
	Rooms      []*RoomUpsert `json:"rooms"`
}

// Authenticated user (owner or agent).
type User struct {
	ID         string      `json:"id"`
	Role       UserRole    `json:"role"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Phone      *string     `json:"phone,omitempty"`
	CreatedAt  string      `json:"createdAt"`
	UpdatedAt  string      `json:"updatedAt"`
	Properties []*Property `json:"properties,omitempty"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

// Bed taxonomy (extend as needed).
type BedType string

const (
	BedTypeKing         BedType = "KING"
	BedTypeQueen        BedType = "QUEEN"
	BedTypeFull         BedType = "FULL"
	BedTypeTwin         BedType = "TWIN"
	BedTypeSofaBedFull  BedType = "SOFA_BED_FULL"
	BedTypeSofaBedQueen BedType = "SOFA_BED_QUEEN"
	BedTypeBunk         BedType = "BUNK"
	BedTypeTwinXl       BedType = "TWIN_XL"
	BedTypeCrib         BedType = "CRIB"
	BedTypeAirMattress  BedType = "AIR_MATTRESS"
)

var AllBedType = []BedType{
	BedTypeKing,
	BedTypeQueen,
	BedTypeFull,
	BedTypeTwin,
	BedTypeSofaBedFull,
	BedTypeSofaBedQueen,
	BedTypeBunk,
	BedTypeTwinXl,
	BedTypeCrib,
	BedTypeAirMattress,
}

func (e BedType) IsValid() bool {
	switch e {
	case BedTypeKing, BedTypeQueen, BedTypeFull, BedTypeTwin, BedTypeSofaBedFull, BedTypeSofaBedQueen, BedTypeBunk, BedTypeTwinXl, BedTypeCrib, BedTypeAirMattress:
		return true
	}
	return false
}

func (e BedType) String() string {
	return string(e)
}

func (e *BedType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BedType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BedType", str)
	}
	return nil
}

func (e BedType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BedType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BedType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sortable fields for properties.
type PropertySortBy string

const (
	PropertySortBySubmittedAt PropertySortBy = "SUBMITTED_AT"
	PropertySortByCreatedAt   PropertySortBy = "CREATED_AT"
	PropertySortByUpdatedAt   PropertySortBy = "UPDATED_AT"
	PropertySortByTitle       PropertySortBy = "TITLE"
	PropertySortByCity        PropertySortBy = "CITY"
	PropertySortByRegion      PropertySortBy = "REGION"
	PropertySortByMaxGuests   PropertySortBy = "MAX_GUESTS"
)

var AllPropertySortBy = []PropertySortBy{
	PropertySortBySubmittedAt,
	PropertySortByCreatedAt,
	PropertySortByUpdatedAt,
	PropertySortByTitle,
	PropertySortByCity,
	PropertySortByRegion,
	PropertySortByMaxGuests,
}

func (e PropertySortBy) IsValid() bool {
	switch e {
	case PropertySortBySubmittedAt, PropertySortByCreatedAt, PropertySortByUpdatedAt, PropertySortByTitle, PropertySortByCity, PropertySortByRegion, PropertySortByMaxGuests:
		return true
	}
	return false
}

func (e PropertySortBy) String() string {
	return string(e)
}

func (e *PropertySortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PropertySortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PropertySortBy", str)
	}
	return nil
}

func (e PropertySortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PropertySortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PropertySortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Lifecycle of a listing.
type PropertyStatus string

const (
	PropertyStatusDraft       PropertyStatus = "DRAFT"
	PropertyStatusSubmitted   PropertyStatus = "SUBMITTED"
	PropertyStatusUnderReview PropertyStatus = "UNDER_REVIEW"
	PropertyStatusApproved    PropertyStatus = "APPROVED"
	PropertyStatusRejected    PropertyStatus = "REJECTED"
)

var AllPropertyStatus = []PropertyStatus{
	PropertyStatusDraft,
	PropertyStatusSubmitted,
	PropertyStatusUnderReview,
	PropertyStatusApproved,
	PropertyStatusRejected,
}

func (e PropertyStatus) IsValid() bool {
	switch e {
	case PropertyStatusDraft, PropertyStatusSubmitted, PropertyStatusUnderReview, PropertyStatusApproved, PropertyStatusRejected:
		return true
	}
	return false
}

func (e PropertyStatus) String() string {
	return string(e)
}

func (e *PropertyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PropertyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PropertyStatus", str)
	}
	return nil
}

func (e PropertyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PropertyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PropertyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Inventory type.
type PropertyType string

const (
	PropertyTypeHouse     PropertyType = "HOUSE"
	PropertyTypeApartment PropertyType = "APARTMENT"
	PropertyTypeCondo     PropertyType = "CONDO"
	PropertyTypeCabin     PropertyType = "CABIN"
	PropertyTypeVilla     PropertyType = "VILLA"
	PropertyTypeTownhouse PropertyType = "TOWNHOUSE"
	PropertyTypeOther     PropertyType = "OTHER"
)

var AllPropertyType = []PropertyType{
	PropertyTypeHouse,
	PropertyTypeApartment,
	PropertyTypeCondo,
	PropertyTypeCabin,
	PropertyTypeVilla,
	PropertyTypeTownhouse,
	PropertyTypeOther,
}

func (e PropertyType) IsValid() bool {
	switch e {
	case PropertyTypeHouse, PropertyTypeApartment, PropertyTypeCondo, PropertyTypeCabin, PropertyTypeVilla, PropertyTypeTownhouse, PropertyTypeOther:
		return true
	}
	return false
}

func (e PropertyType) String() string {
	return string(e)
}

func (e *PropertyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PropertyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PropertyType", str)
	}
	return nil
}

func (e PropertyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PropertyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PropertyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewDecision string

const (
	ReviewDecisionApprove       ReviewDecision = "APPROVE"
	ReviewDecisionReject        ReviewDecision = "REJECT"
	ReviewDecisionReturnForEdit ReviewDecision = "RETURN_FOR_EDIT"
)

var AllReviewDecision = []ReviewDecision{
	ReviewDecisionApprove,
	ReviewDecisionReject,
	ReviewDecisionReturnForEdit,
}

func (e ReviewDecision) IsValid() bool {
	switch e {
	case ReviewDecisionApprove, ReviewDecisionReject, ReviewDecisionReturnForEdit:
		return true
	}
	return false
}

func (e ReviewDecision) String() string {
	return string(e)
}

func (e *ReviewDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewDecision", str)
	}
	return nil
}

func (e ReviewDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Auth roles.
type UserRole string

const (
	UserRoleOwner UserRole = "OWNER"
	UserRoleAgent UserRole = "AGENT"
)

var AllUserRole = []UserRole{
	UserRoleOwner,
	UserRoleAgent,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleOwner, UserRoleAgent:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
