// Code generated by ent, DO NOT EDIT.

package room

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPropertyID holds the string denoting the property_id field in the database.
	FieldPropertyID = "property_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFloorLabel holds the string denoting the floor_label field in the database.
	FieldFloorLabel = "floor_label"
	// FieldAreaSqFt holds the string denoting the area_sq_ft field in the database.
	FieldAreaSqFt = "area_sq_ft"
	// FieldBedMix holds the string denoting the bed_mix field in the database.
	FieldBedMix = "bed_mix"
	// FieldEnsuiteBath holds the string denoting the ensuite_bath field in the database.
	FieldEnsuiteBath = "ensuite_bath"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProperty holds the string denoting the property edge name in mutations.
	EdgeProperty = "property"
	// Table holds the table name of the room in the database.
	Table = "rooms"
	// PropertyTable is the table that holds the property relation/edge.
	PropertyTable = "rooms"
	// PropertyInverseTable is the table name for the Property entity.
	// It exists in this package in order to avoid circular dependency with the "property" package.
	PropertyInverseTable = "properties"
	// PropertyColumn is the table column denoting the property relation/edge.
	PropertyColumn = "property_id"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldPropertyID,
	FieldName,
	FieldFloorLabel,
	FieldAreaSqFt,
	FieldBedMix,
	FieldEnsuiteBath,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// AreaSqFtValidator is a validator for the "area_sq_ft" field. It is called by the builders before save.
	AreaSqFtValidator func(int) error
	// DefaultBedMix holds the default value on creation for the "bed_mix" field.
	DefaultBedMix map[string]int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Room queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPropertyID orders the results by the property_id field.
func ByPropertyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPropertyID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFloorLabel orders the results by the floor_label field.
func ByFloorLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFloorLabel, opts...).ToFunc()
}

// ByAreaSqFt orders the results by the area_sq_ft field.
func ByAreaSqFt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAreaSqFt, opts...).ToFunc()
}

// ByEnsuiteBath orders the results by the ensuite_bath field.
func ByEnsuiteBath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnsuiteBath, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPropertyField orders the results by property field.
func ByPropertyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPropertyStep(), sql.OrderByField(field, opts...))
	}
}
func newPropertyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PropertyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PropertyTable, PropertyColumn),
	)
}
