// Code generated by ent, DO NOT EDIT.

package room

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/evolve-interviews/paxtonedgar-case-study/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldID, id))
}

// PropertyID applies equality check predicate on the "property_id" field. It's identical to PropertyIDEQ.
func PropertyID(v uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldPropertyID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldName, v))
}

// FloorLabel applies equality check predicate on the "floor_label" field. It's identical to FloorLabelEQ.
func FloorLabel(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldFloorLabel, v))
}

// AreaSqFt applies equality check predicate on the "area_sq_ft" field. It's identical to AreaSqFtEQ.
func AreaSqFt(v int) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldAreaSqFt, v))
}

// EnsuiteBath applies equality check predicate on the "ensuite_bath" field. It's identical to EnsuiteBathEQ.
func EnsuiteBath(v bool) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldEnsuiteBath, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldUpdatedAt, v))
}

// PropertyIDEQ applies the EQ predicate on the "property_id" field.
func PropertyIDEQ(v uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldPropertyID, v))
}

// PropertyIDNEQ applies the NEQ predicate on the "property_id" field.
func PropertyIDNEQ(v uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldPropertyID, v))
}

// PropertyIDIn applies the In predicate on the "property_id" field.
func PropertyIDIn(vs ...uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldPropertyID, vs...))
}

// PropertyIDNotIn applies the NotIn predicate on the "property_id" field.
func PropertyIDNotIn(vs ...uuid.UUID) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldPropertyID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Room {
	return predicate.Room(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Room {
	return predicate.Room(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Room {
	return predicate.Room(sql.FieldContainsFold(FieldName, v))
}

// FloorLabelEQ applies the EQ predicate on the "floor_label" field.
func FloorLabelEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldFloorLabel, v))
}

// FloorLabelNEQ applies the NEQ predicate on the "floor_label" field.
func FloorLabelNEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldFloorLabel, v))
}

// FloorLabelIn applies the In predicate on the "floor_label" field.
func FloorLabelIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldFloorLabel, vs...))
}

// FloorLabelNotIn applies the NotIn predicate on the "floor_label" field.
func FloorLabelNotIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldFloorLabel, vs...))
}

// FloorLabelGT applies the GT predicate on the "floor_label" field.
func FloorLabelGT(v string) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldFloorLabel, v))
}

// FloorLabelGTE applies the GTE predicate on the "floor_label" field.
func FloorLabelGTE(v string) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldFloorLabel, v))
}

// FloorLabelLT applies the LT predicate on the "floor_label" field.
func FloorLabelLT(v string) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldFloorLabel, v))
}

// FloorLabelLTE applies the LTE predicate on the "floor_label" field.
func FloorLabelLTE(v string) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldFloorLabel, v))
}

// FloorLabelContains applies the Contains predicate on the "floor_label" field.
func FloorLabelContains(v string) predicate.Room {
	return predicate.Room(sql.FieldContains(FieldFloorLabel, v))
}

// FloorLabelHasPrefix applies the HasPrefix predicate on the "floor_label" field.
func FloorLabelHasPrefix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasPrefix(FieldFloorLabel, v))
}

// FloorLabelHasSuffix applies the HasSuffix predicate on the "floor_label" field.
func FloorLabelHasSuffix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasSuffix(FieldFloorLabel, v))
}

// FloorLabelIsNil applies the IsNil predicate on the "floor_label" field.
func FloorLabelIsNil() predicate.Room {
	return predicate.Room(sql.FieldIsNull(FieldFloorLabel))
}

// FloorLabelNotNil applies the NotNil predicate on the "floor_label" field.
func FloorLabelNotNil() predicate.Room {
	return predicate.Room(sql.FieldNotNull(FieldFloorLabel))
}

// FloorLabelEqualFold applies the EqualFold predicate on the "floor_label" field.
func FloorLabelEqualFold(v string) predicate.Room {
	return predicate.Room(sql.FieldEqualFold(FieldFloorLabel, v))
}

// FloorLabelContainsFold applies the ContainsFold predicate on the "floor_label" field.
func FloorLabelContainsFold(v string) predicate.Room {
	return predicate.Room(sql.FieldContainsFold(FieldFloorLabel, v))
}

// AreaSqFtEQ applies the EQ predicate on the "area_sq_ft" field.
func AreaSqFtEQ(v int) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldAreaSqFt, v))
}

// AreaSqFtNEQ applies the NEQ predicate on the "area_sq_ft" field.
func AreaSqFtNEQ(v int) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldAreaSqFt, v))
}

// AreaSqFtIn applies the In predicate on the "area_sq_ft" field.
func AreaSqFtIn(vs ...int) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldAreaSqFt, vs...))
}

// AreaSqFtNotIn applies the NotIn predicate on the "area_sq_ft" field.
func AreaSqFtNotIn(vs ...int) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldAreaSqFt, vs...))
}

// AreaSqFtGT applies the GT predicate on the "area_sq_ft" field.
func AreaSqFtGT(v int) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldAreaSqFt, v))
}

// AreaSqFtGTE applies the GTE predicate on the "area_sq_ft" field.
func AreaSqFtGTE(v int) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldAreaSqFt, v))
}

// AreaSqFtLT applies the LT predicate on the "area_sq_ft" field.
func AreaSqFtLT(v int) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldAreaSqFt, v))
}

// AreaSqFtLTE applies the LTE predicate on the "area_sq_ft" field.
func AreaSqFtLTE(v int) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldAreaSqFt, v))
}

// AreaSqFtIsNil applies the IsNil predicate on the "area_sq_ft" field.
func AreaSqFtIsNil() predicate.Room {
	return predicate.Room(sql.FieldIsNull(FieldAreaSqFt))
}

// AreaSqFtNotNil applies the NotNil predicate on the "area_sq_ft" field.
func AreaSqFtNotNil() predicate.Room {
	return predicate.Room(sql.FieldNotNull(FieldAreaSqFt))
}

// EnsuiteBathEQ applies the EQ predicate on the "ensuite_bath" field.
func EnsuiteBathEQ(v bool) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldEnsuiteBath, v))
}

// EnsuiteBathNEQ applies the NEQ predicate on the "ensuite_bath" field.
func EnsuiteBathNEQ(v bool) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldEnsuiteBath, v))
}

// EnsuiteBathIsNil applies the IsNil predicate on the "ensuite_bath" field.
func EnsuiteBathIsNil() predicate.Room {
	return predicate.Room(sql.FieldIsNull(FieldEnsuiteBath))
}

// EnsuiteBathNotNil applies the NotNil predicate on the "ensuite_bath" field.
func EnsuiteBathNotNil() predicate.Room {
	return predicate.Room(sql.FieldNotNull(FieldEnsuiteBath))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Room {
	return predicate.Room(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Room {
	return predicate.Room(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Room {
	return predicate.Room(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Room {
	return predicate.Room(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Room {
	return predicate.Room(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Room {
	return predicate.Room(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Room {
	return predicate.Room(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Room {
	return predicate.Room(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Room {
	return predicate.Room(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProperty applies the HasEdge predicate on the "property" edge.
func HasProperty() predicate.Room {
	return predicate.Room(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PropertyTable, PropertyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPropertyWith applies the HasEdge predicate on the "property" edge with a given conditions (other predicates).
func HasPropertyWith(preds ...predicate.Property) predicate.Room {
	return predicate.Room(func(s *sql.Selector) {
		step := newPropertyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Room) predicate.Room {
	return predicate.Room(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Room) predicate.Room {
	return predicate.Room(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Room) predicate.Room {
	return predicate.Room(sql.NotPredicates(p))
}
